import { defineRecipe } from "./utils";

export const breakfastRecipes = [
  defineRecipe({
    slug: "whipped-cottage-cheese-berry-bowl",
    title: "Whipped Cottage Cheese Berry Bowl",
    summary: "A creamy, high-protein breakfast that tastes more like dessert than meal prep.",
    category: "breakfast",
    tags: ["high-protein", "high-fibre", "no-cook"],
    activeMinutes: 10,
    totalMinutes: 10,
    servings: 1,
    nutrition: { calories: 328, protein: 32.5, fibre: 7 },
    ingredients: ["1 cup cottage cheese", "1/2 teaspoon vanilla", "1 cup berries", "1 tablespoon chopped almonds", "Optional cinnamon or honey"],
    steps: ["Blend the cottage cheese and vanilla until smooth.", "Spoon into a bowl and top with berries and almonds.", "Finish with cinnamon or a small drizzle of honey if desired."],
    storage: "Assemble the cottage-cheese base for up to 3 days; add fruit just before eating.",
    substitutions: ["Use Greek yogurt for a tangier bowl.", "Use frozen berries thawed overnight."],
    shortcut: "Blend two or three portions at once and portion into jars.",
    contentAngle: "Film the cottage cheese going from lumpy to silky, then build the bowl in three quick layers.",
    source: { label: "Skinnytaste — Whipped Cottage Cheese Bowls", url: "https://www.skinnytaste.com/high-protein-whipped-cottage-cheese-bowls/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "cottage-cheese-scrambled-eggs",
    title: "Cottage-Cheese Scrambled Eggs",
    summary: "Fluffy eggs with extra protein and a five-minute cook time.",
    category: "breakfast",
    tags: ["high-protein", "high-fibre"],
    activeMinutes: 6,
    totalMinutes: 6,
    servings: 2,
    nutrition: { calories: 173, protein: 17.5 },
    ingredients: ["4 large eggs", "1/2 cup cottage cheese", "1 teaspoon olive-oil spray", "Black pepper", "Optional spinach, mushrooms, or peppers"],
    steps: ["Whisk eggs, cottage cheese, and pepper.", "Warm a non-stick skillet over medium heat and add the spray.", "Pour in the eggs, fold slowly until just set, and add vegetables if using."],
    storage: "Best fresh; cooked eggs can be refrigerated for 2 days and reheated gently.",
    substitutions: ["Use egg whites for a lighter version.", "Add smoked salmon or leftover chicken for more protein."],
    shortcut: "Keep chopped vegetables in the freezer so the whole breakfast is one pan.",
    contentAngle: "A six-minute breakfast timer on screen makes the speed immediately believable.",
    source: { label: "Skinnytaste — High-Protein Scrambled Eggs", url: "https://www.skinnytaste.com/high-protein-scrambled-eggs-with-cottage-cheese/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "high-protein-oat-waffles",
    title: "High-Protein Oat Waffles",
    summary: "Cottage cheese, oats, and eggs blended into freezer-friendly waffles.",
    category: "breakfast",
    tags: ["high-protein", "make-ahead", "freezer-friendly"],
    activeMinutes: 15,
    totalMinutes: 15,
    servings: 5,
    nutrition: { calories: 121, protein: 8.5, fibre: 1.5 },
    ingredients: ["Cottage cheese", "Eggs", "Oat flour or blended rolled oats", "Vanilla", "Baking powder", "Fruit for topping"],
    steps: ["Blend the wet ingredients and oats into a smooth batter.", "Fold in whipped egg whites if you want a lighter texture.", "Cook in a hot waffle iron until golden and crisp."],
    storage: "Refrigerate cooked waffles for 4 days or freeze them in a single layer; toast to reheat.",
    substitutions: ["Use berries, banana, or stewed apple as toppings.", "Use gluten-free oats if needed."],
    shortcut: "Make the batter on Sunday and cook only what you need each morning.",
    contentAngle: "Show the blender-to-waffle-iron transition and finish with a protein tally on screen.",
    source: { label: "Skinnytaste — Protein Waffles", url: "https://www.skinnytaste.com/high-protein-oat-waffles/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "egg-white-turkey-bacon-muffins",
    title: "Egg-White Turkey Bacon Muffins",
    summary: "Grab-and-go egg muffins packed with vegetables, cottage cheese, and turkey bacon.",
    category: "breakfast",
    tags: ["high-protein", "make-ahead", "freezer-friendly"],
    activeMinutes: 15,
    totalMinutes: 50,
    servings: 6,
    nutrition: { calories: 144, protein: 20, fibre: 1 },
    ingredients: ["Egg whites", "Cottage cheese", "Turkey bacon", "Bell pepper", "Broccoli", "Scallions", "A little shredded cheddar"],
    steps: ["Cook the turkey bacon and chop the vegetables.", "Whisk egg whites with cottage cheese and seasoning.", "Fill a greased muffin tin, top with bacon and cheese, and bake until set."],
    storage: "Refrigerate up to 4 days or freeze cooled muffins for up to 2 months.",
    substitutions: ["Use chopped chicken sausage or leftover roasted vegetables.", "Use whole eggs instead of egg whites."],
    shortcut: "Use frozen chopped broccoli and pre-cooked turkey bacon.",
    contentAngle: "Film a Sunday batch, then a weekday grab-and-go cut that reinforces the meal-prep payoff.",
    source: { label: "Skinnytaste — High Protein Egg-White Muffins", url: "https://www.skinnytaste.com/egg-white-muffins/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "cottage-cheese-chicken-sausage-frittata",
    title: "Cottage-Cheese Chicken Sausage Frittata",
    summary: "A one-pan egg bake with spinach and chicken sausage that reheats beautifully.",
    category: "breakfast",
    tags: ["high-protein", "make-ahead"],
    activeMinutes: 10,
    totalMinutes: 30,
    servings: 4,
    nutrition: { calories: 233, protein: 21.5, fibre: 0.5 },
    ingredients: ["Eggs", "Cottage cheese", "Chicken sausage", "Baby spinach", "Parmesan or Pecorino", "Black pepper"],
    steps: ["Brown the sliced sausage in an oven-safe skillet.", "Add spinach until wilted, then pour over the whisked egg and cottage-cheese mixture.", "Bake until the centre is set and slice into portions."],
    storage: "Refrigerate portions for 3–4 days; reheat in short microwave bursts.",
    substitutions: ["Use mushrooms, peppers, or leftover greens.", "Swap sausage for smoked salmon or beans."],
    shortcut: "Use a bag of baby spinach and pre-cooked chicken sausage.",
    contentAngle: "Cut the finished frittata into four boxes to make the storage story visual.",
    source: { label: "Skinnytaste — Cottage Cheese Egg and Sausage Frittata", url: "https://www.skinnytaste.com/cottage-cheese-egg-and-sausage-frittata/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "apple-pie-overnight-oats",
    title: "Apple-Pie Overnight Oats",
    summary: "A no-cook jar that turns oats, yogurt, apple, and cinnamon into a weekday breakfast.",
    category: "breakfast",
    tags: ["high-fibre", "no-cook", "make-ahead"],
    activeMinutes: 5,
    totalMinutes: 480,
    servings: 4,
    ingredients: ["Rolled oats", "Plain Greek yogurt", "Milk", "Diced apple", "Cinnamon", "Chia seeds", "Optional walnuts"],
    steps: ["Stir oats, yogurt, milk, chia, and cinnamon in a jar.", "Fold through diced apple and chill overnight.", "Top with walnuts or extra yogurt before eating."],
    storage: "Refrigerate in sealed jars for up to 4 days.",
    substitutions: ["Use pear or frozen berries instead of apple.", "Use dairy-free yogurt and milk if needed."],
    shortcut: "Mix four jars in under ten minutes while dinner is cooking.",
    contentAngle: "Use a top-down jar layer shot and a morning fridge grab to show zero morning cooking.",
    source: { label: "Budget Bytes — Apple Pie Overnight Oats", url: "https://www.budgetbytes.com/no-sugar-added-apple-pie-overnight-oats/" },
  }),
  defineRecipe({
    slug: "tropical-yogurt-oat-parfaits",
    title: "Tropical Yogurt-Oat Parfaits",
    summary: "Layered yogurt, oats, banana, pineapple, mango, and coconut for an easy make-ahead breakfast.",
    category: "breakfast",
    tags: ["high-fibre", "no-cook", "make-ahead"],
    activeMinutes: 15,
    totalMinutes: 15,
    servings: 4,
    nutrition: { calories: 317, protein: 7.7, fibre: 5.8 },
    ingredients: ["Rolled oats", "Plain or vanilla yogurt", "Banana", "Pineapple", "Mango", "Unsweetened coconut"],
    steps: ["Layer oats and yogurt in four jars.", "Add banana, pineapple, and mango between the layers.", "Finish with coconut and chill overnight."],
    storage: "Refrigerate for up to 5 days; stir before eating.",
    substitutions: ["Use berries and peaches in colder months.", "Use Greek yogurt to raise protein, adding a splash of milk if needed."],
    shortcut: "Use frozen mango and pre-cut pineapple.",
    contentAngle: "A bright layered jar is ideal for a clean cover frame and a fast assembly reel.",
    source: { label: "Budget Bytes — Tropical Yogurt Parfaits", url: "https://www.budgetbytes.com/tropical-yogurt-parfaits/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "blueberry-banana-baked-oatmeal",
    title: "Blueberry-Banana Baked Oatmeal",
    summary: "A soft, scoopable oat bake that turns a weekend prep into several breakfasts.",
    category: "breakfast",
    tags: ["high-fibre", "make-ahead", "freezer-friendly"],
    activeMinutes: 15,
    totalMinutes: 60,
    servings: 6,
    ingredients: ["Rolled oats", "Milk", "Plain yogurt", "Egg", "Banana", "Blueberries", "Cinnamon"],
    steps: ["Add banana and berries to a greased baking dish.", "Whisk the wet ingredients, then stir in oats and cinnamon.", "Pour over the fruit and bake until set."],
    storage: "Refrigerate portions for 5 days or freeze squares for up to 2 months.",
    substitutions: ["Use peaches, apples, or frozen mixed berries.", "Add hemp hearts or chopped nuts."],
    shortcut: "Bake while preparing another meal and cool overnight before slicing.",
    contentAngle: "Film the scoopable texture and show three different toppings from one batch.",
    source: { label: "Budget Bytes — Baked Oatmeal", url: "https://www.budgetbytes.com/baked-oatmeal/" },
  }),
  defineRecipe({
    slug: "breakfast-burrito-bowl",
    title: "Freezer Breakfast Burrito Bowl",
    summary: "Eggs, potatoes, black beans, salsa, and cheese in a reheatable bowl instead of a messy wrap.",
    category: "breakfast",
    tags: ["high-protein", "make-ahead", "freezer-friendly"],
    activeMinutes: 20,
    totalMinutes: 35,
    servings: 4,
    nutrition: { protein: 25, fibre: 8 },
    ingredients: ["Eggs", "Roasted potatoes", "Black beans", "Bell pepper", "Salsa", "Shredded cheese", "Scallions"],
    steps: ["Roast or pan-cook the potatoes and peppers.", "Scramble the eggs and warm the beans.", "Layer potatoes, eggs, beans, salsa, and cheese into containers."],
    storage: "Refrigerate up to 4 days or freeze without fresh salsa for up to 2 months.",
    substitutions: ["Use turkey sausage or tofu scramble.", "Swap potatoes for brown rice."],
    shortcut: "Use frozen roasted potatoes and microwave rice.",
    contentAngle: "Show one base becoming four different bowls with toppings changed for variety.",
    source: { label: "Budget Bytes — Breakfast Meal Prep Ideas", url: "https://www.budgetbytes.com/make-ahead-breakfast-recipes/" },
  }),
  defineRecipe({
    slug: "peanut-butter-banana-protein-smoothie",
    title: "Peanut-Butter Banana Breakfast Smoothie",
    summary: "A five-minute blender breakfast with yogurt, banana, oats, and peanut butter.",
    category: "breakfast",
    tags: ["high-protein", "high-fibre", "no-cook"],
    activeMinutes: 5,
    totalMinutes: 5,
    servings: 1,
    nutrition: { protein: 24, fibre: 7 },
    ingredients: ["Greek yogurt", "Banana", "Rolled oats", "Peanut butter", "Milk", "Cinnamon", "Ice"],
    steps: ["Add everything to a blender.", "Blend until smooth and adjust thickness with milk.", "Serve immediately or chill in a sealed bottle."],
    storage: "Best fresh; refrigerated smoothie keeps for one day and should be shaken before drinking.",
    substitutions: ["Use powdered peanut butter for fewer calories.", "Use berries instead of banana."],
    shortcut: "Freeze banana slices and portion oats into small bags ahead of time.",
    contentAngle: "Use a single continuous blender shot with ingredient callouts timed to the pour.",
    source: { label: "Budget Bytes — Cold Breakfast Recipes", url: "https://www.budgetbytes.com/category/recipes/breakfast/cold-breakfast-recipes/" },
  }),
  defineRecipe({
    slug: "lemon-berry-yogurt-bowl",
    title: "Lemon-Berry Yogurt Bowl",
    summary: "Greek yogurt, lemon zest, berries, oats, and seeds for a bright five-minute breakfast.",
    category: "breakfast",
    tags: ["high-protein", "high-fibre", "no-cook"],
    activeMinutes: 5,
    totalMinutes: 5,
    servings: 1,
    nutrition: { protein: 24, fibre: 6 },
    ingredients: ["Plain Greek yogurt", "Mixed berries", "Rolled oats or granola", "Chia or ground flax", "Lemon zest", "Optional honey"],
    steps: ["Stir lemon zest into the yogurt.", "Top with berries, oats, and seeds.", "Add honey only if the berries need extra sweetness."],
    storage: "Prepare the yogurt base for 3 days; add crunchy toppings at serving.",
    substitutions: ["Use orange zest or cinnamon.", "Use pumpkin seeds instead of chia."],
    shortcut: "Keep a topping jar beside the yogurt in the fridge.",
    contentAngle: "A spoon drag through the lemony yogurt makes a strong close-up texture shot.",
    source: { label: "Budget Bytes — Lemon Berry Yogurt Breakfast Bowls", url: "https://www.budgetbytes.com/lemon-berry-yogurt-breakfast-bowls/" },
  }),
  defineRecipe({
    slug: "banana-nut-protein-oats",
    title: "Banana-Nut Protein Oats",
    summary: "Warm oats with banana, Greek yogurt, and nuts that keep breakfast simple and filling.",
    category: "breakfast",
    tags: ["high-protein", "high-fibre", "quick" as never],
    activeMinutes: 10,
    totalMinutes: 10,
    servings: 1,
    nutrition: { protein: 25, fibre: 7 },
    ingredients: ["Rolled oats", "Milk", "Greek yogurt", "Banana", "Walnuts", "Cinnamon"],
    steps: ["Simmer oats and milk until creamy.", "Stir in half the banana and cinnamon.", "Top with yogurt, remaining banana, and walnuts."],
    storage: "Refrigerate cooked oats for up to 3 days; loosen with milk when reheating.",
    substitutions: ["Use apple and pecans.", "Use sunflower-seed butter for a nut-free version."],
    shortcut: "Make a dry oat-and-cinnamon mix for the week.",
    contentAngle: "Show the bowl before and after the yogurt swirl to make the protein add-on obvious.",
    source: { label: "Skinnytaste — High-Protein Breakfast Ideas", url: "https://www.skinnytaste.com/high-protein-breakfast-ideas/" },
  }),
];
