import { defineRecipe } from "./utils";

export const dinnerRecipes = [
  defineRecipe({
    slug: "buffalo-chicken-rice-bowls",
    title: "Buffalo Chicken Rice Bowls",
    summary: "Chicken, brown rice, black beans, cheese, and hot sauce in a high-protein prep bowl.",
    category: "dinner",
    tags: ["high-protein", "high-fibre", "make-ahead"],
    activeMinutes: 30,
    totalMinutes: 30,
    servings: 6,
    nutrition: { calories: 485, protein: 49.5, fat: 16, carbs: 36, fibre: 7 },
    ingredients: ["2 1/2 pounds chicken breast, diced", "3 cups cooked brown rice", "2 cups black beans, rinsed", "1 cup buffalo sauce", "1 medium red onion, diced", "1 1/2 cups shredded cheddar", "6 scallions, sliced"],
    steps: ["Cook the chicken with onion and buffalo sauce.", "Warm the beans and prepare the rice.", "Layer rice, beans, chicken, cheese, and scallions into bowls."],
    storage: "Refrigerate up to 4 days; microwave until hot and add fresh toppings after reheating.",
    substitutions: ["Use turkey or tofu.", "Use quinoa or roasted potatoes instead of rice."],
    shortcut: "Use microwave brown rice and rotisserie chicken tossed with buffalo sauce.",
    contentAngle: "A bold orange sauce pour and six-bowl meal-prep grid will stop the scroll.",
    source: { label: "Skinnytaste — Buffalo Chicken Rice Bowls", url: "https://www.skinnytaste.com/buffalo-chicken-rice-bowls/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "chicken-taco-rice-bowls",
    title: "Chicken Taco Rice Bowls",
    summary: "Seared chicken thighs, black beans, rice, pico, and avocado for an easy family dinner.",
    category: "dinner",
    tags: ["high-protein", "high-fibre", "make-ahead", "freezer-friendly"],
    activeMinutes: 30,
    totalMinutes: 30,
    servings: 6,
    nutrition: { calories: 550, protein: 45.5, fat: 20, carbs: 47, fibre: 9.5 },
    ingredients: ["2 pounds chicken thighs", "3 cups cooked rice", "2 cups black beans, rinsed", "2 cups pico de gallo", "2 avocados, diced", "2 tablespoons taco seasoning", "2 limes, cut into wedges"],
    steps: ["Season and sear the chicken, then slice.", "Warm beans and rice while the chicken rests.", "Build bowls and finish with pico, avocado, and lime."],
    storage: "Refrigerate bowls for up to 4 days; freeze the chicken, rice, and beans for up to 3 months without fresh toppings.",
    substitutions: ["Use chicken breast, turkey, or tofu.", "Use corn tortillas for taco-style leftovers."],
    shortcut: "Use microwave rice, canned beans, and store-bought pico.",
    contentAngle: "Film the bowl in layers, ending with avocado and a lime squeeze.",
    source: { label: "Skinnytaste — Chicken Taco Bowls", url: "https://www.skinnytaste.com/chicken-taco-bowls/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "ground-turkey-vegetable-stir-fry",
    title: "Ground Turkey Vegetable Stir-Fry",
    summary: "A one-skillet turkey and vegetable dinner that works with rice, noodles, or lettuce cups.",
    category: "dinner",
    tags: ["high-protein", "one-pan", "make-ahead"],
    activeMinutes: 25,
    totalMinutes: 25,
    servings: 4,
    nutrition: { calories: 367, protein: 32, fat: 13, carbs: 31, fibre: 4 },
    ingredients: ["1 1/2 pounds ground turkey", "6 cups frozen stir-fry vegetables", "4 garlic cloves, minced", "1 tablespoon grated ginger", "1/4 cup soy sauce", "2 tablespoons rice vinegar", "3 cups cooked brown rice"],
    steps: ["Brown turkey in a large skillet.", "Add vegetables, garlic, and ginger and cook until crisp-tender.", "Finish with soy and vinegar; serve over rice."],
    storage: "Refrigerate for up to 4 days; reheat in a skillet with a splash of water.",
    substitutions: ["Use ground chicken, lean beef, or crumbled tempeh.", "Add edamame for more fibre and protein."],
    shortcut: "Use a frozen stir-fry blend and pre-cooked rice.",
    contentAngle: "One pan, one spatula, one finished bowl is an easy 20-second edit.",
    source: { label: "Budget Bytes — Ground Turkey Stir-Fry", url: "https://www.budgetbytes.com/ground-turkey-stir-fry/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "chicken-shawarma-sheet-pan",
    title: "Chicken Shawarma Sheet Pan",
    summary: "Spiced chicken, chickpeas, and vegetables roasted together for maximum flavour and minimal cleanup.",
    category: "dinner",
    tags: ["high-protein", "high-fibre", "one-pan", "make-ahead"],
    activeMinutes: 15,
    totalMinutes: 45,
    servings: 4,
    nutrition: { calories: 371, protein: 40, fat: 13, carbs: 23, fibre: 7.5 },
    ingredients: ["1 1/2 pounds boneless chicken thighs", "1 1/2 cups chickpeas, rinsed", "4 cups cauliflower florets", "1 bell pepper, sliced", "1 red onion, sliced", "2 tablespoons shawarma spices", "1 cup Greek yogurt", "1 lemon, juiced"],
    steps: ["Toss chicken, chickpeas, and vegetables with spices and oil spray.", "Roast on one tray until browned and cooked through.", "Serve with yogurt sauce, pita, or grains."],
    storage: "Refrigerate for up to 4 days; store yogurt sauce separately.",
    substitutions: ["Use chicken breast or tofu.", "Use broccoli, zucchini, or frozen vegetables."],
    shortcut: "Use rotisserie chicken and roast only the chickpeas and vegetables.",
    contentAngle: "A sheet-pan sizzle followed by a cool yogurt drizzle gives contrast and appetite appeal.",
    source: { label: "Skinnytaste — Chicken Shawarma Sheet-Pan Dinner", url: "https://www.skinnytaste.com/chicken-shawarma-sheet-pan-dinner/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "shrimp-fajita-bowls",
    title: "Shrimp Fajita Bowls",
    summary: "Fast shrimp, peppers, onions, rice, and beans for a bright weeknight bowl.",
    category: "dinner",
    tags: ["high-protein", "high-fibre", "one-pan"],
    activeMinutes: 25,
    totalMinutes: 30,
    servings: 4,
    nutrition: { calories: 431, protein: 26, fat: 17, carbs: 45, fibre: 8 },
    ingredients: ["1 1/2 pounds peeled shrimp", "3 bell peppers, sliced", "1 large onion, sliced", "1 1/2 cups black beans, rinsed", "3 cups cooked rice", "2 tablespoons fajita seasoning", "2 limes, cut into wedges", "1 avocado, diced"],
    steps: ["Cook peppers and onion until browned.", "Add seasoned shrimp and cook until just opaque.", "Serve with rice, beans, lime, and avocado."],
    storage: "Refrigerate for up to 3 days; reheat shrimp gently to avoid overcooking.",
    substitutions: ["Use chicken, fish, or tofu.", "Use cauliflower rice for a lighter base."],
    shortcut: "Use frozen shrimp, frozen peppers, and microwave rice.",
    contentAngle: "The shrimp changing colour in the pan is a natural visual transition.",
    source: { label: "Skinnytaste — Shrimp Fajita Bowls", url: "https://www.skinnytaste.com/shrimp-fajita-bowls/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "lemon-chili-shrimp-quinoa-bowls",
    title: "Lemon-Chili Shrimp Quinoa Bowls",
    summary: "Shrimp, quinoa, vegetables, avocado, and a lemon-chili finish in a balanced bowl.",
    category: "dinner",
    tags: ["high-protein", "high-fibre", "make-ahead"],
    activeMinutes: 25,
    totalMinutes: 45,
    servings: 4,
    nutrition: { calories: 484, protein: 37, fat: 19, carbs: 40, fibre: 9 },
    ingredients: ["1 1/2 pounds peeled shrimp", "3 cups cooked quinoa", "4 cups broccoli florets", "2 bell peppers, sliced", "1 avocado, diced", "1 lemon, juiced", "1 teaspoon chili flakes", "1/4 cup chopped parsley"],
    steps: ["Cook quinoa and steam or roast the vegetables.", "Sauté shrimp with lemon, garlic, and chili.", "Assemble bowls with quinoa, vegetables, shrimp, and avocado."],
    storage: "Refrigerate for up to 3 days; add avocado after reheating.",
    substitutions: ["Use chicken or edamame.", "Use brown rice or farro instead of quinoa."],
    shortcut: "Use microwave quinoa and pre-cut vegetables.",
    contentAngle: "Bright citrus, green vegetables, and pink shrimp give this a strong thumbnail frame.",
    source: { label: "Skinnytaste — Lemon-Chili Shrimp Quinoa Bowls", url: "https://www.skinnytaste.com/shrimp-quinoa-bowl/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "greek-chicken-rice-bowls",
    title: "Greek Chicken Rice Bowls",
    summary: "Lemon-oregano chicken, rice, cucumber, tomato, and yogurt sauce for a prep-friendly dinner.",
    category: "dinner",
    tags: ["high-protein", "make-ahead"],
    activeMinutes: 30,
    totalMinutes: 60,
    servings: 4,
    nutrition: { calories: 418, protein: 44, fat: 14, carbs: 27, fibre: 2.5 },
    ingredients: ["1 1/2 pounds chicken breast", "2 cups cooked rice", "1 medium cucumber, diced", "2 medium tomatoes, diced", "1 cup Greek yogurt", "1 lemon, juiced", "2 garlic cloves, minced", "1 teaspoon dried oregano", "1/2 cup crumbled feta"],
    steps: ["Marinate chicken with lemon, garlic, and oregano.", "Cook chicken and rice; stir together the yogurt sauce.", "Build bowls with vegetables and feta added after reheating."],
    storage: "Refrigerate for up to 4 days; store sauce and vegetables separately.",
    substitutions: ["Use chickpeas or tofu.", "Use quinoa or potatoes as the base."],
    shortcut: "Use rotisserie chicken and microwave rice.",
    contentAngle: "A four-container meal-prep grid and a single sauce spoon make this easy to copy.",
    source: { label: "Skinnytaste — Greek Chicken Meal-Prep Rice Bowls", url: "https://www.skinnytaste.com/greek-chicken-meal-prep-rice-bowls/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "marry-me-chicken-meatballs",
    title: "Marry-Me Chicken Meatballs",
    summary: "Tender chicken meatballs in a tomato, spinach, garlic, and Parmesan sauce.",
    category: "dinner",
    tags: ["high-protein", "freezer-friendly", "make-ahead"],
    activeMinutes: 25,
    totalMinutes: 45,
    servings: 5,
    nutrition: { calories: 367, protein: 31, fat: 19, carbs: 18, fibre: 3 },
    ingredients: ["1 1/2 pounds ground chicken", "1 large egg", "1/2 cup breadcrumbs", "1/2 cup chopped sun-dried tomatoes", "3 garlic cloves, minced", "2 cups baby spinach", "1 1/2 cups crushed tomatoes", "1/2 cup grated Parmesan"],
    steps: ["Mix and shape the meatballs.", "Brown them in a skillet, then simmer in the tomato sauce.", "Wilt in spinach and finish with Parmesan."],
    storage: "Refrigerate for 3–4 days; freeze cooked meatballs for up to 3 months and thaw overnight.",
    substitutions: ["Use ground turkey.", "Serve with pasta, polenta, rice, or crusty bread."],
    shortcut: "Use frozen meatballs and add the tomato-spinach sauce.",
    contentAngle: "A single meatball cut open over the sauce is a strong appetite shot.",
    source: { label: "Budget Bytes — Marry-Me Chicken Meatballs", url: "https://www.budgetbytes.com/marry-me-chicken-meatballs/" },
  }),
  defineRecipe({
    slug: "chicken-piccata-meatball-orzo",
    title: "Chicken Piccata Meatball Orzo Skillet",
    summary: "Lemon, capers, chicken meatballs, and orzo cooked together in one skillet.",
    category: "dinner",
    tags: ["high-protein", "one-pan", "make-ahead"],
    activeMinutes: 25,
    totalMinutes: 45,
    servings: 4,
    nutrition: { calories: 427, protein: 30, fat: 15, carbs: 43, fibre: 3 },
    ingredients: ["1 1/4 pounds ground chicken", "1 1/2 cups dry orzo", "2 lemons, juiced", "1/4 cup capers, drained", "3 garlic cloves, minced", "1/2 cup grated Parmesan", "3 cups chicken broth", "2 cups trimmed green beans"],
    steps: ["Mix and brown chicken meatballs.", "Add garlic, orzo, broth, lemon, and capers to the same skillet.", "Simmer until the orzo is tender and the meatballs are cooked through."],
    storage: "Refrigerate for 3–4 days; loosen with broth when reheating. Freeze meatballs separately for best texture.",
    substitutions: ["Use turkey meatballs.", "Use rice-shaped cauliflower or small pasta."],
    shortcut: "Shape meatballs the night before so dinner is a one-pan finish.",
    contentAngle: "The lemon squeeze over a glossy skillet is a polished finishing frame.",
    source: { label: "Budget Bytes — Chicken Piccata Meatballs and Orzo Skillet", url: "https://www.budgetbytes.com/chicken-piccata-meatballs-and-orzo-skillet/" },
  }),
  defineRecipe({
    slug: "easy-turkey-chili",
    title: "Easy Turkey and Bean Chili",
    summary: "Lean turkey, beans, tomatoes, and peppers in a batch that improves after a night in the fridge.",
    category: "dinner",
    tags: ["high-protein", "high-fibre", "freezer-friendly", "make-ahead"],
    activeMinutes: 20,
    totalMinutes: 50,
    servings: 6,
    nutrition: { calories: 331, protein: 29, fat: 9, carbs: 33, fibre: 13 },
    ingredients: ["2 pounds lean ground turkey", "1 (15-ounce) can kidney beans, rinsed", "1 (15-ounce) can black beans, rinsed", "2 (14-ounce) cans crushed tomatoes", "1 bell pepper, diced", "1 large onion, diced", "2 tablespoons chili powder", "2 teaspoons ground cumin"],
    steps: ["Brown the turkey with onion and pepper.", "Add beans, tomatoes, and spices.", "Simmer until thick, then serve with yogurt, scallions, or avocado."],
    storage: "Refrigerate for 4 days or freeze portions for up to 3 months.",
    substitutions: ["Use lentils or extra beans instead of turkey.", "Use chicken or lean beef."],
    shortcut: "Use frozen diced onion and canned beans; simmer on the stovetop while rice cooks.",
    contentAngle: "A pot-to-container sequence makes batch cooking feel practical, not restrictive.",
    source: { label: "Budget Bytes — Turkey Chili", url: "https://www.budgetbytes.com/turkey-chili/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "mediterranean-turkey-bowls",
    title: "Mediterranean Turkey Bowls",
    summary: "Seasoned turkey, rice, cucumbers, tomatoes, and beans with a bright yogurt finish.",
    category: "dinner",
    tags: ["high-protein", "high-fibre", "make-ahead"],
    activeMinutes: 30,
    totalMinutes: 35,
    servings: 4,
    nutrition: { calories: 403, protein: 34, fat: 13, carbs: 36, fibre: 5 },
    ingredients: ["1 1/2 pounds ground turkey", "2 cups cooked rice", "1 1/2 cups chickpeas, rinsed", "1 medium cucumber, diced", "2 medium tomatoes, diced", "1 cup Greek yogurt", "1 lemon, juiced", "1/4 cup chopped parsley", "1/2 cup crumbled feta"],
    steps: ["Brown turkey with garlic, oregano, and lemon.", "Warm rice and chickpeas; chop the vegetables.", "Layer bowls and finish with yogurt sauce and feta."],
    storage: "Refrigerate for up to 4 days; keep fresh vegetables and sauce separate.",
    substitutions: ["Use chicken, lentils, or tofu.", "Use quinoa or couscous instead of rice."],
    shortcut: "Use microwave rice, canned chickpeas, and pre-cooked turkey.",
    contentAngle: "The same base can be shown as a bowl, pita, and salad for a content series.",
    source: { label: "Budget Bytes — Mediterranean Turkey Bowls", url: "https://www.budgetbytes.com/mediterranean-turkey-bowls/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "ground-turkey-zucchini-skillet",
    title: "Ground Turkey and Zucchini Skillet",
    summary: "A fast turkey, zucchini, tomato, and herb skillet that works over rice or potatoes.",
    category: "dinner",
    tags: ["high-protein", "one-pan"],
    activeMinutes: 25,
    totalMinutes: 25,
    servings: 4,
    nutrition: { calories: 230, protein: 29, fat: 10, carbs: 8, fibre: 1 },
    ingredients: ["1 1/2 pounds ground turkey", "3 medium zucchini, diced", "1 medium onion, diced", "2 cups crushed tomatoes", "3 garlic cloves, minced", "2 teaspoons Italian seasoning", "1/4 cup grated Parmesan"],
    steps: ["Brown turkey and onion.", "Add zucchini, garlic, tomatoes, and seasoning.", "Simmer until the zucchini is tender; finish with Parmesan."],
    storage: "Refrigerate for up to 4 days; serve over rice, pasta, or potatoes.",
    substitutions: ["Use mushrooms, peppers, or spinach.", "Add white beans for more fibre."],
    shortcut: "Use jarred tomato sauce and frozen zucchini spirals.",
    contentAngle: "A simple skillet with a single bold colour accent gives this everyday dinner a clean frame.",
    source: { label: "Budget Bytes — Ground Turkey Zucchini Skillet", url: "https://www.budgetbytes.com/ground-turkey-zucchini-skillet/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "vegan-quinoa-edamame-bowl",
    title: "Quinoa and Edamame Power Bowl",
    summary: "Quinoa, edamame, roasted vegetables, and a lemon-tahini dressing for a plant-forward dinner.",
    category: "dinner",
    tags: ["high-protein", "high-fibre", "vegetarian", "make-ahead"],
    activeMinutes: 25,
    totalMinutes: 45,
    servings: 4,
    nutrition: { calories: 376, protein: 20, fat: 16, carbs: 38, fibre: 10 },
    ingredients: ["3 cups cooked quinoa", "2 cups shelled edamame", "4 cups broccoli florets", "2 medium carrots, sliced", "1 medium cucumber, diced", "1/3 cup tahini", "2 lemons, juiced", "1/4 cup pumpkin seeds"],
    steps: ["Cook quinoa and roast the vegetables.", "Whisk tahini, lemon, water, and salt into a sauce.", "Assemble bowls with edamame, vegetables, quinoa, and seeds."],
    storage: "Refrigerate for up to 4 days; keep sauce separate.",
    substitutions: ["Use tofu or chickpeas.", "Use brown rice or farro instead of quinoa."],
    shortcut: "Use microwave quinoa and frozen edamame.",
    contentAngle: "A plant-forward bowl widens the audience without changing the practical message.",
    source: { label: "Skinnytaste — Vegan Quinoa Bowl", url: "https://www.skinnytaste.com/vegan-quinoa-bowl/", note: "Cooper Fitness adaptation from the source recipe." },
  }),
  defineRecipe({
    slug: "honey-sriracha-chicken-broccoli-bowls",
    title: "Honey-Sriracha Chicken and Broccoli Bowls",
    summary: "Sweet-spicy chicken and roasted broccoli over rice, all prepared on one sheet pan.",
    category: "dinner",
    tags: ["high-protein", "one-pan", "make-ahead"],
    activeMinutes: 15,
    totalMinutes: 35,
    servings: 4,
    nutrition: { calories: 396, protein: 38, fat: 8, carbs: 43, fibre: 5 },
    ingredients: ["1 1/2 pounds chicken breast, diced", "4 cups broccoli florets", "3 cups cooked rice", "1/4 cup honey", "3 tablespoons sriracha", "1/4 cup soy sauce", "3 garlic cloves, minced", "1 lime, juiced"],
    steps: ["Whisk honey, sriracha, soy, garlic, and lime.", "Toss chicken and broccoli with the sauce on a sheet pan.", "Roast until cooked and serve over rice."],
    storage: "Refrigerate for up to 4 days; keep extra sauce separate.",
    substitutions: ["Use tofu or shrimp.", "Use maple syrup or a mild chili sauce."],
    shortcut: "Use frozen broccoli and microwave rice.",
    contentAngle: "The glossy sauce makes a satisfying close-up while the single-pan promise sells the recipe.",
    source: { label: "Skinnytaste — Sheet-Pan Dinners", url: "https://www.skinnytaste.com/easy-sheet-pan-dinners/", note: "Cooper Fitness adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "salmon-vegetable-sheet-pan",
    title: "Lemon Salmon and Vegetable Tray",
    summary: "Salmon, potatoes, green beans, and lemon roasted together for a low-effort dinner.",
    category: "dinner",
    tags: ["high-protein", "one-pan", "make-ahead"],
    activeMinutes: 10,
    totalMinutes: 35,
    servings: 4,
    nutrition: { calories: 435, protein: 34, fat: 19, carbs: 32, fibre: 5 },
    ingredients: ["4 (5-ounce) salmon fillets", "1 1/2 pounds baby potatoes, halved", "12 ounces green beans, trimmed", "1 lemon, sliced", "3 garlic cloves, minced", "2 tablespoons chopped dill", "1 teaspoon olive-oil spray"],
    steps: ["Start the potatoes on the tray until nearly tender.", "Add salmon and green beans with lemon and garlic.", "Roast until the salmon flakes and finish with dill."],
    storage: "Refrigerate for up to 3 days; reheat gently or serve chilled over greens.",
    substitutions: ["Use cod, trout, or chicken.", "Use asparagus or broccoli instead of beans."],
    shortcut: "Use microwave baby potatoes and frozen green beans.",
    contentAngle: "A tray-to-plate reveal works well for a calm, cinematic kitchen reel.",
    source: { label: "Skinnytaste — One-Pan Meals", url: "https://www.skinnytaste.com/recipes/one-pan/", note: "Cooper Fitness sheet-pan adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "turkey-meatball-marinara-bowls",
    title: "Turkey Meatball Marinara Bowls",
    summary: "Lean turkey meatballs, marinara, whole-grain pasta, and spinach for a family-friendly dinner.",
    category: "dinner",
    tags: ["high-protein", "make-ahead", "freezer-friendly"],
    activeMinutes: 25,
    totalMinutes: 45,
    servings: 5,
    nutrition: { calories: 403, protein: 32, fat: 15, carbs: 35, fibre: 6 },
    ingredients: ["1 1/2 pounds lean ground turkey", "1 large egg", "1/2 cup oats or breadcrumbs", "3 garlic cloves, minced", "3 cups marinara sauce", "8 ounces whole-grain pasta", "4 cups baby spinach", "1/2 cup grated Parmesan"],
    steps: ["Mix and shape meatballs.", "Bake or pan-sear, then simmer in marinara.", "Serve with pasta and wilted spinach."],
    storage: "Refrigerate for 4 days; freeze meatballs and sauce for up to 2 months.",
    substitutions: ["Use chicken meatballs or lentil balls.", "Use zucchini noodles or polenta."],
    shortcut: "Use frozen turkey meatballs and jarred marinara.",
    contentAngle: "A family dinner that doubles as freezer prep makes this highly shareable.",
    source: { label: "Budget Bytes — Easy Homemade Meatballs", url: "https://www.budgetbytes.com/homemade-meatballs/", note: "Cooper Fitness turkey adaptation from the source method." },
  }),
  defineRecipe({
    slug: "shrimp-cabbage-roll-bowl",
    title: "Shrimp Cabbage Roll Bowl",
    summary: "Garlic shrimp, cabbage, carrots, and rice with a quick sesame-soy finish.",
    category: "dinner",
    tags: ["high-protein", "high-fibre", "one-pan"],
    activeMinutes: 20,
    totalMinutes: 25,
    servings: 4,
    nutrition: { calories: 375, protein: 35, fat: 10, carbs: 37, fibre: 6 },
    ingredients: ["1 1/2 pounds peeled shrimp", "6 cups shredded cabbage", "2 medium carrots, shredded", "2 cups cooked rice", "3 garlic cloves, minced", "1 tablespoon grated ginger", "1/4 cup soy sauce", "2 tablespoons sesame seeds"],
    steps: ["Sauté shrimp with garlic and ginger; remove from the pan.", "Cook cabbage and carrots until just tender.", "Return shrimp, add soy, and serve over rice."],
    storage: "Refrigerate for up to 3 days; reheat quickly so shrimp stay tender.",
    substitutions: ["Use ground turkey or tofu.", "Use cauliflower rice or soba noodles."],
    shortcut: "Use coleslaw mix and frozen shrimp.",
    contentAngle: "The cabbage volume shrinking in the skillet provides a satisfying visual payoff.",
    source: { label: "TikTok high-protein recipe discovery", url: "https://www.tiktok.com/channel/high-protein-vegetables?lang=en", note: "Social inspiration only; nutrition is a Cooper Fitness estimate." },
  }),
  defineRecipe({
    slug: "cottage-cheese-sweet-potato-beef-bowl",
    title: "Cottage-Cheese Sweet-Potato Beef Bowl",
    summary: "Seasoned beef, sweet potato, cottage cheese, avocado, and hot sauce in a colourful bowl.",
    category: "dinner",
    tags: ["high-protein", "high-fibre", "make-ahead"],
    activeMinutes: 20,
    totalMinutes: 35,
    servings: 4,
    nutrition: { calories: 459, protein: 33, fat: 24, carbs: 27, fibre: 6 },
    ingredients: ["1 1/2 pounds lean ground beef", "3 medium sweet potatoes, cubed", "2 cups cottage cheese", "1 avocado, diced", "2 tablespoons hot sauce", "2 tablespoons hot honey", "3 scallions, sliced"],
    steps: ["Roast or microwave sweet potatoes until soft.", "Brown the beef with smoked paprika, garlic, and pepper.", "Layer sweet potato, beef, cottage cheese, avocado, and hot sauce."],
    storage: "Refrigerate beef and sweet potato for 4 days; add cottage cheese and avocado after reheating.",
    substitutions: ["Use ground turkey or lentils.", "Use baked potato or brown rice."],
    shortcut: "Use microwave sweet potatoes and pre-cooked beef.",
    contentAngle: "The cottage cheese spoonful on top is the unexpected hook for a social-native recipe.",
    source: { label: "Eating Bird Food — Facebook bowl inspiration", url: "https://www.facebook.com/eatingbirdfood/posts/officially-obsessed-with-the-viral-cottage-cheese-sweet-ptoato-beef-bowl-its-del/1153829613063019/", note: "Social inspiration; nutrition is creator-supplied and approximate." },
  }),
];
