import { defineRecipe } from "./utils";

export const lunchRecipes = [
  defineRecipe({
    slug: "tuna-white-bean-salad",
    title: "Tuna and White-Bean Salad",
    summary: "A bright, no-cook lunch built from tuna, navy beans, greens, and lemon-Dijon dressing.",
    category: "lunch",
    tags: ["high-protein", "high-fibre", "no-cook", "make-ahead"],
    activeMinutes: 15,
    totalMinutes: 15,
    servings: 2,
    nutrition: { calories: 437, protein: 38, fibre: 12 },
    ingredients: ["Canned tuna", "Navy beans", "Mixed greens", "Red onion", "Capers or pickles", "Lemon", "Dijon", "Olive oil", "Dill"],
    steps: ["Whisk lemon, Dijon, olive oil, garlic, salt, and pepper.", "Fold tuna, beans, onion, capers, and dill through the dressing.", "Serve over greens and add crunch from cucumber or peppers."],
    storage: "Refrigerate the dressed salad for up to 3 days; keep greens separate for best texture.",
    substitutions: ["Use chickpeas instead of navy beans.", "Use canned salmon or shredded chicken."],
    shortcut: "Use pre-washed greens and canned beans; the only knife work is the onion.",
    contentAngle: "Start with the pantry shelf, then cut to a ten-minute finished lunch.",
    source: { label: "Skinnytaste — Tuna and White-Bean Salad", url: "https://www.skinnytaste.com/tuna-and-white-bean-salad/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "green-goddess-chicken-chickpea-salad",
    title: "Green-Goddess Chicken and Chickpea Salad",
    summary: "Crisp vegetables, chicken, chickpeas, and a herby yogurt dressing with no stove required.",
    category: "lunch",
    tags: ["high-protein", "high-fibre", "no-cook", "make-ahead"],
    activeMinutes: 25,
    totalMinutes: 25,
    servings: 4,
    nutrition: { calories: 326, protein: 30, fibre: 6 },
    ingredients: ["Cooked chicken", "Chickpeas", "Romaine or kale", "Cucumber", "Bell pepper", "Green onions", "Greek yogurt", "Lemon", "Fresh herbs"],
    steps: ["Blend or finely chop the yogurt, lemon, herbs, and seasoning into a dressing.", "Chop the vegetables and shred the chicken.", "Toss everything with chickpeas and dress just before serving."],
    storage: "Keep dressed salad refrigerated for 2 days; store dressing separately for a 4-day prep.",
    substitutions: ["Use rotisserie turkey or canned salmon.", "Use white beans for the chickpeas."],
    shortcut: "Buy a rotisserie chicken and a bottled green-goddess dressing with simple ingredients.",
    contentAngle: "Use a colour-first overhead shot: greens, chickpeas, chicken, then the dressing pour.",
    source: { label: "Skinnytaste — Green Goddess Chicken Chickpea Salad", url: "https://www.skinnytaste.com/green-goddess-chicken-chickpea-salad/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "asian-chicken-chili-crisp-salad",
    title: "Asian Chicken Salad with Chili-Crisp Dressing",
    summary: "Cabbage, chicken, mandarin, avocado, and a spicy-savoury dressing that holds up for lunch prep.",
    category: "lunch",
    tags: ["high-protein", "high-fibre", "make-ahead"],
    activeMinutes: 35,
    totalMinutes: 35,
    servings: 4,
    nutrition: { calories: 371, protein: 26.5, fibre: 6 },
    ingredients: ["Cooked chicken", "Napa cabbage", "Mandarin oranges", "Avocado", "Carrots", "Cucumber", "Chili crisp", "Rice vinegar", "Soy sauce"],
    steps: ["Whisk chili crisp, vinegar, soy, and lime into a dressing.", "Slice cabbage and vegetables; add chicken and oranges.", "Toss individual portions with dressing and avocado at serving."],
    storage: "Store undressed salad for 4 days; add avocado and crispy toppings just before eating.",
    substitutions: ["Use shredded turkey or tofu.", "Use orange segments or apple instead of mandarin."],
    shortcut: "Use bagged slaw mix and pre-cooked chicken.",
    contentAngle: "A crunch sound design cut—cabbage, carrot, and chili crisp—will make this stand out.",
    source: { label: "Skinnytaste — Asian Chicken Salad", url: "https://www.skinnytaste.com/asian-chicken-salad/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "five-ingredient-salmon-salad",
    title: "Five-Ingredient Salmon Salad",
    summary: "A quick salmon lunch that turns a can or pouch of fish into a proper meal.",
    category: "lunch",
    tags: ["high-protein", "no-cook"],
    activeMinutes: 15,
    totalMinutes: 15,
    servings: 2,
    nutrition: { protein: 28, fibre: 4 },
    ingredients: ["Canned salmon", "Greek yogurt", "Celery", "Lemon", "Dill", "Whole-grain crackers or greens"],
    steps: ["Flake the salmon into a bowl.", "Stir in yogurt, celery, lemon, dill, and pepper.", "Serve in lettuce cups, over greens, or with whole-grain crackers."],
    storage: "Refrigerate for up to 3 days in an airtight container.",
    substitutions: ["Use tuna or leftover cooked salmon.", "Use cucumber or bell pepper instead of celery."],
    shortcut: "Use a salmon pouch and pre-cut vegetables.",
    contentAngle: "Show three serving formats from the same base to make the recipe feel versatile.",
    source: { label: "Skinnytaste — High-Protein Meals", url: "https://www.skinnytaste.com/high-protein/", note: "Cooper Fitness adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "classic-greek-yogurt-chicken-salad",
    title: "Greek-Yogurt Chicken Salad",
    summary: "A lighter, protein-forward chicken salad with celery, grapes, and toasted nuts.",
    category: "lunch",
    tags: ["high-protein", "make-ahead"],
    activeMinutes: 10,
    totalMinutes: 10,
    servings: 4,
    nutrition: { protein: 30, fibre: 3 },
    ingredients: ["Cooked chicken", "Greek yogurt", "Celery", "Grapes or apple", "Almonds", "Dijon", "Lemon", "Whole-grain bread or greens"],
    steps: ["Mix yogurt, Dijon, lemon, salt, and pepper.", "Fold in chicken, celery, fruit, and almonds.", "Chill briefly and serve in a sandwich, wrap, or lettuce cup."],
    storage: "Refrigerate for up to 4 days; keep bread separate.",
    substitutions: ["Use pumpkin seeds instead of almonds.", "Use cranberries or diced pear for the fruit."],
    shortcut: "Use rotisserie chicken and a handful of pre-cut grapes.",
    contentAngle: "Film the same filling becoming a wrap, salad, and lunchbox snack.",
    source: { label: "Skinnytaste — High-Protein Meals", url: "https://www.skinnytaste.com/high-protein/", note: "Cooper Fitness adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "tuna-egg-salad-crunch-box",
    title: "Tuna-Egg Salad Crunch Box",
    summary: "A high-protein lunchbox with tuna, eggs, crunchy vegetables, and a simple yogurt dressing.",
    category: "lunch",
    tags: ["high-protein", "make-ahead"],
    activeMinutes: 15,
    totalMinutes: 15,
    servings: 2,
    nutrition: { protein: 31, fibre: 4 },
    ingredients: ["Canned tuna", "Hard-boiled eggs", "Greek yogurt", "Celery", "Pickles", "Mustard", "Cucumber", "Whole-grain crackers"],
    steps: ["Chop the eggs and celery.", "Fold with tuna, yogurt, mustard, pickles, and pepper.", "Pack with cucumber and crackers in separate compartments."],
    storage: "Refrigerate the salad for up to 3 days; assemble lunchboxes the night before.",
    substitutions: ["Use canned salmon or shredded chicken.", "Use white beans for half the tuna."],
    shortcut: "Keep boiled eggs ready in the fridge and use a pouch of tuna.",
    contentAngle: "A lunchbox packing shot makes the portion and portability clear.",
    source: { label: "Skinnytaste — High-Protein Meals", url: "https://www.skinnytaste.com/high-protein/", note: "Cooper Fitness adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "lentil-crunch-salad",
    title: "Lentil Crunch Salad",
    summary: "Lentils, carrots, celery, peppers, parsley, and lemon for a fibre-forward lunch.",
    category: "lunch",
    tags: ["high-fibre", "vegetarian", "make-ahead"],
    activeMinutes: 20,
    totalMinutes: 35,
    servings: 4,
    nutrition: { calories: 181, protein: 10, fibre: 5.5 },
    ingredients: ["Cooked lentils", "Carrot", "Celery", "Bell pepper", "Red onion", "Parsley", "Lemon", "Olive oil", "Optional feta"],
    steps: ["Combine lentils and chopped vegetables.", "Whisk lemon, olive oil, salt, and pepper.", "Toss, add parsley and feta, and chill before serving."],
    storage: "Refrigerate for up to 3 days; the flavour improves overnight.",
    substitutions: ["Use canned lentils or chickpeas.", "Add tuna, chicken, or boiled eggs for more protein."],
    shortcut: "Use vacuum-packed cooked lentils and pre-diced vegetables.",
    contentAngle: "A bright chopping board sequence makes fibre-rich ingredients feel effortless.",
    source: { label: "Skinnytaste — Lentil Salad", url: "https://www.skinnytaste.com/lentil-salad/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "mediterranean-bean-salad",
    title: "Mediterranean Bean Salad",
    summary: "Three beans, cucumber, tomato, olives, and feta in a lemon-herb dressing.",
    category: "lunch",
    tags: ["high-fibre", "vegetarian", "no-cook", "make-ahead"],
    activeMinutes: 15,
    totalMinutes: 15,
    servings: 4,
    nutrition: { protein: 12, fibre: 10 },
    ingredients: ["Chickpeas", "White beans", "Black beans", "Cucumber", "Cherry tomatoes", "Olives", "Feta", "Lemon", "Parsley"],
    steps: ["Rinse and drain the beans.", "Chop the vegetables and toss with beans, feta, and olives.", "Dress with lemon, olive oil, and herbs."],
    storage: "Refrigerate for up to 4 days; add greens or pita when serving.",
    substitutions: ["Use any combination of canned beans.", "Add canned tuna or chicken for a higher-protein version."],
    shortcut: "Use a frozen or pre-chopped Mediterranean vegetable mix.",
    contentAngle: "Use a colour-blocked ingredient laydown and one bowl toss.",
    source: { label: "Skinnytaste — High-Fibre Lunch Ideas", url: "https://www.skinnytaste.com/high-fiber-recipes/high-fiber-lunch/", note: "Cooper Fitness adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "thai-inspired-chicken-slaw",
    title: "Thai-Inspired Chicken Slaw",
    summary: "A crunchy cabbage lunch with chicken, herbs, lime, and a peanut-lime dressing.",
    category: "lunch",
    tags: ["high-protein", "high-fibre", "make-ahead"],
    activeMinutes: 20,
    totalMinutes: 20,
    servings: 4,
    nutrition: { protein: 28, fibre: 5 },
    ingredients: ["Cooked chicken", "Shredded cabbage", "Carrots", "Cucumber", "Cilantro", "Lime", "Peanut butter", "Soy sauce", "Chili flakes"],
    steps: ["Whisk peanut butter, lime, soy, water, and chili into a pourable dressing.", "Toss cabbage, carrots, cucumber, herbs, and chicken.", "Dress individual portions before eating."],
    storage: "Keep slaw and dressing separate for up to 4 days.",
    substitutions: ["Use tofu or edamame instead of chicken.", "Use sunflower-seed butter for a nut-free version."],
    shortcut: "Start with bagged coleslaw mix and leftover chicken.",
    contentAngle: "Film the dressing loosening with lime water—an easy visual hook.",
    source: { label: "Skinnytaste — High-Fibre Lunch Ideas", url: "https://www.skinnytaste.com/high-fiber-recipes/high-fiber-lunch/", note: "Cooper Fitness adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "chicken-egg-roll-bowl",
    title: "Chicken Egg-Roll Bowl",
    summary: "Ground chicken, cabbage, carrots, and ginger in one skillet with all the takeout flavour.",
    category: "lunch",
    tags: ["high-protein", "high-fibre", "one-pan", "make-ahead"],
    activeMinutes: 30,
    totalMinutes: 30,
    servings: 4,
    nutrition: { protein: 30, fibre: 5 },
    ingredients: ["Ground chicken", "Coleslaw mix", "Carrots", "Garlic", "Ginger", "Soy sauce", "Rice vinegar", "Scallions"],
    steps: ["Brown the chicken in a large skillet.", "Add garlic, ginger, and slaw mix; cook until the cabbage softens.", "Finish with soy, vinegar, and scallions."],
    storage: "Refrigerate for up to 4 days; reheat in a skillet or microwave.",
    substitutions: ["Use ground turkey, lean pork, or crumbled tofu.", "Serve over rice or cauliflower rice."],
    shortcut: "Use bagged slaw and jarred minced garlic/ginger.",
    contentAngle: "A single-pan recipe with a ‘takeout in 30 minutes’ hook fits short-form video well.",
    source: { label: "Skinnytaste — High-Fibre Lunch Ideas", url: "https://www.skinnytaste.com/high-fiber-recipes/high-fiber-lunch/", note: "Cooper Fitness adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "greek-chicken-meal-prep-rice-bowl",
    title: "Greek Chicken Meal-Prep Rice Bowl",
    summary: "Lemon chicken, rice, cucumber, tomato, and yogurt sauce in a lunchbox-ready bowl.",
    category: "lunch",
    tags: ["high-protein", "make-ahead"],
    activeMinutes: 30,
    totalMinutes: 60,
    servings: 4,
    nutrition: { calories: 418, protein: 44, fibre: 2.5 },
    ingredients: ["Chicken breast", "Brown rice", "Lemon", "Cucumber", "Tomato", "Greek yogurt", "Garlic", "Oregano", "Feta"],
    steps: ["Marinate chicken with lemon, garlic, oregano, salt, and pepper.", "Cook the chicken and rice while preparing the yogurt sauce.", "Pack rice, chicken, vegetables, feta, and sauce separately where possible."],
    storage: "Refrigerate bowls for up to 4 days; add cucumber and sauce after reheating.",
    substitutions: ["Use quinoa or potatoes instead of rice.", "Use chickpeas or tofu for a vegetarian bowl."],
    shortcut: "Use microwave brown rice and rotisserie chicken.",
    contentAngle: "A meal-prep grid shot makes four balanced lunches appear in one frame.",
    source: { label: "Skinnytaste — Greek Chicken Meal-Prep Rice Bowls", url: "https://www.skinnytaste.com/greek-chicken-meal-prep-rice-bowls/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "pesto-chicken-vegetable-pasta-salad",
    title: "Pesto Chicken and Vegetable Pasta Salad",
    summary: "A cold pasta salad with chicken, vegetables, pesto, and a simple protein-friendly finish.",
    category: "lunch",
    tags: ["high-protein", "make-ahead"],
    activeMinutes: 20,
    totalMinutes: 25,
    servings: 4,
    nutrition: { protein: 31, fibre: 5 },
    ingredients: ["Cooked chicken", "Whole-grain pasta", "Pesto", "Cherry tomatoes", "Spinach", "Peppers", "Lemon"],
    steps: ["Cook pasta, rinse briefly, and cool.", "Toss with chicken, vegetables, pesto, and lemon.", "Portion into containers and add extra greens before serving."],
    storage: "Refrigerate for up to 4 days; loosen with a splash of water before eating.",
    substitutions: ["Use tuna, white beans, or chickpeas.", "Use pesto yogurt sauce to reduce richness."],
    shortcut: "Use rotisserie chicken, microwave pasta, and jarred pesto.",
    contentAngle: "A colourful meal-prep container that eats cold is ideal for workday content.",
    source: { label: "Budget Bytes — Easy Lunch Ideas", url: "https://www.budgetbytes.com/easy-lunch-ideas/", note: "Cooper Fitness adaptation from the meal-prep collection." },
  }),
];
