import { defineRecipe } from "./utils";

export const mealPrepRecipes = [
  defineRecipe({
    slug: "lemon-dijon-yogurt-dressing",
    title: "Lemon-Dijon Yogurt Dressing",
    summary: "A two-minute sauce that makes chicken, beans, grain bowls, and salads taste finished.",
    category: "staple",
    tags: ["high-protein", "no-cook", "make-ahead"],
    activeMinutes: 5,
    totalMinutes: 5,
    servings: 6,
    nutrition: { protein: 2 },
    ingredients: ["1 1/2 cups Greek yogurt", "1 lemon, juiced and zested", "2 tablespoons Dijon mustard", "1 garlic clove, minced", "1 tablespoon olive oil", "2 tablespoons water", "1/4 teaspoon black pepper"],
    steps: ["Whisk everything until smooth.", "Add water a teaspoon at a time until it pours.", "Taste and adjust lemon, salt, and pepper."],
    storage: "Refrigerate in a sealed jar for up to 5 days.",
    substitutions: ["Use tahini for a dairy-free version.", "Add herbs, hot sauce, or honey for a different direction."],
    shortcut: "Shake all ingredients in a jar so there is no extra bowl to wash.",
    contentAngle: "Make one sauce and show three different meals it upgrades.",
    source: { label: "Skinnytaste — Tuna and White-Bean Salad", url: "https://www.skinnytaste.com/tuna-and-white-bean-salad/", note: "Cooper Fitness sauce adaptation from the source dressing." },
  }),
  defineRecipe({
    slug: "green-goddess-yogurt-sauce",
    title: "Green-Goddess Yogurt Sauce",
    summary: "A fresh herb sauce for bowls, wraps, roasted vegetables, and leftover chicken.",
    category: "staple",
    tags: ["high-protein", "no-cook", "make-ahead"],
    activeMinutes: 8,
    totalMinutes: 8,
    servings: 8,
    ingredients: ["1 1/2 cups Greek yogurt", "1/2 cup fresh parsley", "1/4 cup fresh cilantro", "2 green onions, sliced", "1 lemon, juiced", "1 garlic clove, minced", "1/4 cup water", "1/2 teaspoon salt"],
    steps: ["Blend or finely chop the herbs, garlic, lemon, and yogurt.", "Thin with water until spoonable.", "Taste, chill, and use across the week."],
    storage: "Refrigerate for up to 4 days.",
    substitutions: ["Use spinach or basil for part of the herbs.", "Use dairy-free yogurt if needed."],
    shortcut: "Use a small food processor and keep the sauce in a squeeze bottle.",
    contentAngle: "The green sauce pour is a high-colour, high-contrast finishing shot.",
    source: { label: "Skinnytaste — Green Goddess Chicken Chickpea Salad", url: "https://www.skinnytaste.com/green-goddess-chicken-chickpea-salad/", note: "Cooper Fitness sauce adaptation from the source dressing." },
  }),
  defineRecipe({
    slug: "freezer-brown-rice-quinoa-blend",
    title: "Freezer Brown-Rice and Quinoa Blend",
    summary: "A batch of grains portioned for bowls, stir-fries, breakfast bowls, and quick dinners.",
    category: "meal-prep",
    tags: ["high-fibre", "make-ahead", "freezer-friendly"],
    activeMinutes: 10,
    totalMinutes: 35,
    servings: 8,
    nutrition: { fibre: 4 },
    ingredients: ["1 1/2 cups dry brown rice", "3/4 cup dry quinoa", "4 cups water or broth", "1 teaspoon salt", "1 tablespoon lemon zest or 2 tablespoons chopped herbs (optional)"],
    steps: ["Rinse the grains and cook together in a rice cooker or pot.", "Cool quickly on a tray.", "Portion into containers or freezer bags and label by cup measure."],
    storage: "Refrigerate up to 4 days or freeze portions for up to 2 months.",
    substitutions: ["Use farro, barley, or microwaveable grain pouches.", "Add chopped herbs after reheating."],
    shortcut: "Buy frozen cooked grains and portion them immediately after shopping.",
    contentAngle: "A freezer drawer of labelled grain portions makes the consistency message tangible.",
    source: { label: "Budget Bytes — Meal Prep 101", url: "https://www.budgetbytes.com/meal-prep-101-a-beginners-guide/", note: "Cooper Fitness batch-cooking adaptation." },
  }),
  defineRecipe({
    slug: "sheet-pan-roasted-vegetables",
    title: "Sheet-Pan Roasted Vegetables",
    summary: "A flexible tray of vegetables that adds colour, fibre, and volume to almost any meal.",
    category: "meal-prep",
    tags: ["high-fibre", "one-pan", "make-ahead"],
    activeMinutes: 10,
    totalMinutes: 35,
    servings: 6,
    nutrition: { fibre: 5 },
    ingredients: ["4 cups broccoli florets", "2 bell peppers, sliced", "2 medium zucchini, sliced", "1 red onion, sliced", "4 medium carrots, sliced", "1 teaspoon olive-oil spray", "1 teaspoon garlic powder", "1 teaspoon smoked paprika"],
    steps: ["Cut vegetables into similar-sized pieces.", "Season on a sheet pan and roast until browned at the edges.", "Cool before portioning with protein and grains."],
    storage: "Refrigerate for up to 4 days; reheat in a skillet, oven, or microwave.",
    substitutions: ["Use cauliflower, green beans, mushrooms, or frozen vegetables.", "Finish with lemon, feta, or yogurt sauce."],
    shortcut: "Use a frozen roasting blend and cook it straight from frozen.",
    contentAngle: "A before-and-after tray shot shows how little hands-on effort creates a week of colour.",
    source: { label: "Skinnytaste — Sheet-Pan Dinners", url: "https://www.skinnytaste.com/easy-sheet-pan-dinners/", note: "Cooper Fitness flexible vegetable-tray adaptation." },
  }),
  defineRecipe({
    slug: "freezer-chicken-turkey-meatballs",
    title: "Freezer Chicken or Turkey Meatballs",
    summary: "A versatile batch that turns pasta, pita, grain bowls, and soup into fast meals.",
    category: "meal-prep",
    tags: ["high-protein", "freezer-friendly", "make-ahead"],
    activeMinutes: 25,
    totalMinutes: 55,
    servings: 8,
    nutrition: { protein: 24 },
    ingredients: ["2 pounds ground chicken or turkey", "1 large egg", "1 cup breadcrumbs", "1/2 cup grated Parmesan", "3 garlic cloves, minced", "2 teaspoons Italian herbs", "1 teaspoon salt and 1/2 teaspoon pepper"],
    steps: ["Mix gently until just combined.", "Shape into small meatballs and bake or pan-sear until cooked through.", "Cool completely before portioning for the fridge or freezer."],
    storage: "Refrigerate cooked meatballs for 4 days or freeze for up to 2 months.",
    substitutions: ["Use oats instead of breadcrumbs.", "Add grated zucchini or spinach for extra vegetables."],
    shortcut: "Use a cookie scoop to portion a full tray quickly.",
    contentAngle: "One batch, four uses: bowl, wrap, pasta, and soup.",
    source: { label: "Budget Bytes — Easy Homemade Meatballs", url: "https://www.budgetbytes.com/homemade-meatballs/", note: "Cooper Fitness lean-meat adaptation from the freezer-friendly method." },
  }),
  defineRecipe({
    slug: "black-bean-corn-salsa",
    title: "Black-Bean and Corn Salsa",
    summary: "A fridge staple that adds fibre and flavour to eggs, bowls, wraps, chicken, and fish.",
    category: "meal-prep",
    tags: ["high-fibre", "vegetarian", "no-cook", "make-ahead"],
    activeMinutes: 10,
    totalMinutes: 10,
    servings: 8,
    nutrition: { fibre: 5, protein: 5 },
    ingredients: ["2 cups black beans, rinsed", "2 cups corn kernels", "2 medium tomatoes, diced", "1/2 small red onion, diced", "1/4 cup chopped cilantro", "2 limes, juiced", "1 jalapeño, minced", "1/2 teaspoon salt"],
    steps: ["Rinse the beans and drain the corn.", "Fold with chopped tomato, onion, cilantro, lime, and jalapeño.", "Chill before spooning over meals."],
    storage: "Refrigerate for up to 4 days.",
    substitutions: ["Use white beans or chickpeas.", "Add avocado only at serving."],
    shortcut: "Use frozen corn thawed under warm water and jarred jalapeños.",
    contentAngle: "Use one spoonful in four different meals to teach the ‘prep once, eat many ways’ idea.",
    source: { label: "Skinnytaste — High-Fibre Lunch Ideas", url: "https://www.skinnytaste.com/high-fiber-recipes/high-fiber-lunch/", note: "Cooper Fitness salsa adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "edamame-hummus-crunch-dip",
    title: "Edamame Hummus Crunch Dip",
    summary: "A quick, high-fibre dip made from frozen edamame, lemon, garlic, and tahini.",
    category: "staple",
    tags: ["high-protein", "high-fibre", "vegetarian", "no-cook"],
    activeMinutes: 10,
    totalMinutes: 10,
    servings: 8,
    nutrition: { calories: 93, protein: 5.5, fibre: 2.5 },
    ingredients: ["3 cups shelled edamame", "1/3 cup tahini", "2 lemons, juiced", "1 garlic clove, minced", "1 tablespoon olive oil", "1/2 cup water", "2 cups carrot and cucumber sticks"],
    steps: ["Thaw the edamame and blend with tahini, lemon, garlic, and water.", "Adjust texture with more water or olive oil.", "Serve with raw vegetables, whole-grain pita, or crackers."],
    storage: "Refrigerate for up to 4 days.",
    substitutions: ["Use chickpeas instead of edamame.", "Use sunflower-seed butter for a tahini-free version."],
    shortcut: "Thaw frozen edamame in the microwave for two minutes.",
    contentAngle: "A bright green dip gives the library a snack shot that is not another beige hummus bowl.",
    source: { label: "Skinnytaste — Edamame Hummus", url: "https://www.skinnytaste.com/edamame-hummus/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "make-ahead-oat-jar-base",
    title: "Make-Ahead Oat-Jar Base",
    summary: "A measured dry mix that turns into overnight oats, hot oats, or a smoothie booster.",
    category: "meal-prep",
    tags: ["high-fibre", "vegetarian", "make-ahead"],
    activeMinutes: 5,
    totalMinutes: 5,
    servings: 6,
    nutrition: { fibre: 5, protein: 7 },
    ingredients: ["3 cups rolled oats", "1/4 cup chia or ground flax", "1/2 cup pumpkin seeds", "2 teaspoons cinnamon", "1/2 cup dried fruit (optional)", "1/2 cup milk powder (optional)"],
    steps: ["Mix the dry ingredients in a large jar.", "Portion into six small jars or bags.", "Add yogurt and milk overnight, or cook with water in the morning."],
    storage: "Keep the dry mix sealed in the pantry for 2 weeks; prepared jars last 4 days in the fridge.",
    substitutions: ["Use sunflower seeds or chopped walnuts.", "Add cocoa, cardamom, or citrus zest for variety."],
    shortcut: "Keep a scoop inside the jar so each portion takes seconds.",
    contentAngle: "One base becomes apple, berry, chocolate, and savoury oats in a four-frame carousel.",
    source: { label: "Budget Bytes — Make-Ahead Seeded Oats", url: "https://www.budgetbytes.com/make-ahead-seeded-oats/", note: "Cooper Fitness oat-base adaptation." },
  }),
];
