import { defineRecipe } from "./utils";

export const snackRecipes = [
  defineRecipe({
    slug: "apple-chia-peanut-butter-pudding",
    title: "Apple Chia Pudding with Peanut Butter",
    summary: "Greek yogurt, chia, apple, and peanut butter make a high-fibre snack that feels substantial.",
    category: "snack",
    tags: ["high-protein", "high-fibre", "make-ahead"],
    activeMinutes: 10,
    totalMinutes: 130,
    servings: 2,
    nutrition: { calories: 373, protein: 24.5, fat: 16, carbs: 34, fibre: 13 },
    ingredients: ["1 1/2 cups Greek yogurt", "1/4 cup chia seeds", "1/2 cup milk", "1 medium apple, finely diced", "2 tablespoons peanut butter", "1 teaspoon cinnamon"],
    steps: ["Stir yogurt, chia, milk, and cinnamon.", "Fold in finely diced apple.", "Chill until thick and finish with peanut butter."],
    storage: "Refrigerate in sealed jars for up to 4 days.",
    substitutions: ["Use pear or berries.", "Use sunflower-seed butter for a nut-free snack."],
    shortcut: "Mix two jars while cleaning up dinner.",
    contentAngle: "The thick spoon lift and peanut-butter ribbon make a satisfying macro-friendly clip.",
    source: { label: "Skinnytaste — Apple Chia Pudding", url: "https://www.skinnytaste.com/apple-chia-pudding/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "greek-cottage-cheese-snack-bowl",
    title: "Greek Cottage-Cheese Snack Bowl",
    summary: "A savoury mini bowl with cottage cheese, cucumber, tomato, herbs, and feta.",
    category: "snack",
    tags: ["high-protein", "vegetarian", "no-cook"],
    activeMinutes: 10,
    totalMinutes: 10,
    servings: 2,
    nutrition: { calories: 186, protein: 21.5, fat: 7, carbs: 8, fibre: 1.5 },
    ingredients: ["2 cups cottage cheese", "1 medium cucumber, diced", "1 cup cherry tomatoes, halved", "1 bell pepper, diced", "1/4 cup sliced olives", "1/2 cup crumbled feta", "2 tablespoons chopped dill", "2 whole-grain pitas"],
    steps: ["Spoon cottage cheese into bowls.", "Add chopped vegetables, olives, feta, and dill.", "Serve with pita or whole-grain crackers."],
    storage: "Prepare the cheese and chopped vegetables up to 3 days ahead; keep pita separate.",
    substitutions: ["Use Greek yogurt or hummus.", "Add chickpeas for more fibre."],
    shortcut: "Use snack-size vegetables from a grocery tray.",
    contentAngle: "A savoury counterpoint to sweet protein bowls helps the library feel inclusive.",
    source: { label: "Skinnytaste — Greek Cottage-Cheese Bowl", url: "https://www.skinnytaste.com/greek-cottage-cheese-bowl/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "edamame-hummus-vegetable-cups",
    title: "Edamame Hummus Vegetable Cups",
    summary: "A portable snack kit with green edamame hummus and crunchy vegetables.",
    category: "snack",
    tags: ["high-protein", "high-fibre", "vegetarian", "no-cook"],
    activeMinutes: 10,
    totalMinutes: 10,
    servings: 8,
    nutrition: { calories: 93, protein: 5.5, fat: 3, carbs: 12, fibre: 2.5 },
    ingredients: ["2 cups edamame hummus", "2 cups carrot sticks", "2 cups cucumber sticks", "2 cups sugar snap peas", "4 ounces whole-grain pita"],
    steps: ["Spoon hummus into small containers.", "Add a handful of vegetables and pita.", "Keep chilled until snack time."],
    storage: "Refrigerate hummus for up to 4 days; cut vegetables last 3–4 days.",
    substitutions: ["Use chickpea hummus.", "Add a boiled egg or turkey slices when you need more protein."],
    shortcut: "Buy pre-cut vegetables and use store-bought edamame hummus.",
    contentAngle: "Five snack cups lined up in the fridge communicate consistency instantly.",
    source: { label: "Skinnytaste — Edamame Hummus", url: "https://www.skinnytaste.com/edamame-hummus/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "loaded-egg-muffin-snack",
    title: "Loaded Egg-Muffin Snack",
    summary: "Mini egg muffins with spinach, tomato, onion, and a little cheese for an easy grab.",
    category: "snack",
    tags: ["high-protein", "make-ahead", "freezer-friendly"],
    activeMinutes: 10,
    totalMinutes: 30,
    servings: 6,
    nutrition: { calories: 165, protein: 14, fat: 10, carbs: 4 },
    ingredients: ["6 large eggs", "2 cups chopped spinach", "1 medium tomato, diced", "1/4 small red onion, diced", "1/2 cup cottage cheese", "1/2 cup shredded cheddar", "1/4 teaspoon black pepper"],
    steps: ["Whisk eggs with cottage cheese and pepper.", "Fold through chopped vegetables.", "Bake in a greased muffin tin until set."],
    storage: "Refrigerate for up to 4 days or freeze cooled muffins for up to 2 months.",
    substitutions: ["Use egg whites, mushrooms, or leftover roasted vegetables.", "Add turkey bacon or chicken sausage."],
    shortcut: "Use frozen spinach squeezed dry and pre-shredded cheese.",
    contentAngle: "A tray pull-out followed by a lunchbox drop makes this a strong habit-building reel.",
    source: { label: "Skinnytaste — Loaded Egg Muffins", url: "https://www.skinnytaste.com/loaded-baked-omelet-muffins/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "berry-cottage-cheese-breakfast-snack",
    title: "Berry Cottage-Cheese Snack Cup",
    summary: "Cottage cheese, berries, seeds, and cinnamon in a two-minute sweet snack cup.",
    category: "snack",
    tags: ["high-protein", "high-fibre", "no-cook"],
    activeMinutes: 5,
    totalMinutes: 5,
    servings: 1,
    nutrition: { calories: 214, protein: 19, fat: 6, carbs: 21, fibre: 4 },
    ingredients: ["3/4 cup cottage cheese", "1 cup berries", "1 tablespoon pumpkin seeds", "1/4 teaspoon cinnamon", "1 teaspoon honey (optional)"],
    steps: ["Spoon cottage cheese into a cup.", "Add berries and seeds.", "Finish with cinnamon and a small amount of honey if needed."],
    storage: "Assemble for up to 2 days; keep seeds separate for crunch.",
    substitutions: ["Use Greek yogurt.", "Use apple or peach instead of berries."],
    shortcut: "Keep frozen berries and single-serve cottage cheese on hand.",
    contentAngle: "This is a perfect ‘two-minute snack’ story with a clean ingredient count.",
    source: { label: "Skinnytaste — Berry Cottage-Cheese Breakfast Bowl", url: "https://www.skinnytaste.com/berry-cottage-cheese-breakfast-bowl/", note: "Cooper Fitness snack adaptation from the source recipe." },
  }),
  defineRecipe({
    slug: "roasted-chickpea-crunch",
    title: "Roasted Chickpea Crunch",
    summary: "Crisp chickpeas seasoned with smoked paprika for a fibre-rich alternative to chips.",
    category: "snack",
    tags: ["high-fibre", "vegetarian", "make-ahead"],
    activeMinutes: 5,
    totalMinutes: 35,
    servings: 4,
    nutrition: { calories: 143, protein: 7, fat: 3, carbs: 22, fibre: 6 },
    ingredients: ["2 (15-ounce) cans chickpeas, rinsed and dried", "1 teaspoon olive-oil spray", "1 teaspoon smoked paprika", "1 teaspoon garlic powder", "1/2 teaspoon salt", "1 teaspoon lemon zest (optional)"],
    steps: ["Rinse and dry chickpeas thoroughly.", "Toss with seasoning and roast until crisp.", "Cool completely before storing so they stay crunchy."],
    storage: "Keep in a loosely covered container at room temperature for 2 days; re-crisp briefly if needed.",
    substitutions: ["Use edamame or broad beans.", "Change seasoning to curry, ranch, or chili-lime."],
    shortcut: "Use canned chickpeas instead of soaking dried beans.",
    contentAngle: "The crunch sound is the hook; keep the ingredient list on screen for accessibility.",
    source: { label: "Food Network — Roasted Chickpeas", url: "https://www.foodnetwork.com/recipes/alton-brown/roasted-chickpeas-recipe-1923768.html", note: "Cooper Fitness canned-chickpea adaptation for speed." },
  }),
  defineRecipe({
    slug: "greek-yogurt-berry-nut-cup",
    title: "Greek Yogurt Berry-Nut Cup",
    summary: "A five-minute yogurt cup with berries, nuts, and a measured drizzle of honey.",
    category: "snack",
    tags: ["high-protein", "high-fibre", "no-cook"],
    activeMinutes: 5,
    totalMinutes: 5,
    servings: 1,
    nutrition: { calories: 250, protein: 19.5, fat: 9, carbs: 20, fibre: 2.5 },
    ingredients: ["3/4 cup plain Greek yogurt", "1 cup berries", "2 tablespoons chopped nuts", "1 tablespoon chia seeds", "1 teaspoon honey"],
    steps: ["Spoon yogurt into a cup.", "Add berries, nuts, and chia.", "Measure honey rather than free-pouring it."],
    storage: "Assemble for up to 2 days; keep nuts separate for texture.",
    substitutions: ["Use cottage cheese or soy yogurt.", "Use seeds instead of nuts."],
    shortcut: "Use frozen berries thawed overnight.",
    contentAngle: "A measuring-spoon shot teaches calorie awareness without making the snack feel restrictive.",
    source: { label: "Skinnytaste — Greek Yogurt with Berries, Nuts, and Honey", url: "https://www.skinnytaste.com/greek-yogurt-with-berries-nuts-and/", note: "Nutrition is the source recipe estimate." },
  }),
  defineRecipe({
    slug: "tuna-cucumber-boats",
    title: "Tuna Cucumber Boats",
    summary: "Tuna mixed with yogurt and pickles spooned into crisp cucumber halves.",
    category: "snack",
    tags: ["high-protein", "high-fibre", "no-cook"],
    activeMinutes: 10,
    totalMinutes: 10,
    servings: 2,
    nutrition: { calories: 144, protein: 23, fat: 4, carbs: 4, fibre: 2 },
    ingredients: ["1 (5-ounce) can tuna, drained", "1/3 cup Greek yogurt", "1/4 cup diced pickles", "1 tablespoon mustard", "2 medium cucumbers, halved", "1 tablespoon chopped dill", "1/4 teaspoon black pepper"],
    steps: ["Mix tuna, yogurt, pickles, mustard, and dill.", "Halve cucumbers and scoop a shallow channel.", "Fill the cucumber boats and serve chilled."],
    storage: "Keep the tuna mixture for 3 days; fill cucumbers at serving.",
    substitutions: ["Use canned salmon or shredded chicken.", "Use bell-pepper halves instead of cucumber."],
    shortcut: "Use tuna pouches and mini cucumbers.",
    contentAngle: "The boat shape gives a familiar tuna salad a more scroll-stopping visual.",
    source: { label: "Skinnytaste — High-Protein Meals", url: "https://www.skinnytaste.com/high-protein/", note: "Cooper Fitness adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "cottage-cheese-caprese-cups",
    title: "Cottage-Cheese Caprese Cups",
    summary: "Cottage cheese, tomatoes, basil, and balsamic in a high-protein savoury snack.",
    category: "snack",
    tags: ["high-protein", "vegetarian", "no-cook"],
    activeMinutes: 8,
    totalMinutes: 8,
    servings: 2,
    nutrition: { calories: 208, protein: 20, fat: 8, carbs: 14, fibre: 2 },
    ingredients: ["1 cup cottage cheese", "1 cup cherry tomatoes, halved", "1/4 cup fresh basil leaves", "1 tablespoon balsamic glaze", "1/4 teaspoon black pepper", "2 ounces whole-grain crackers (optional)"],
    steps: ["Spoon cottage cheese into cups.", "Add halved tomatoes and basil.", "Finish with a measured balsamic drizzle and pepper."],
    storage: "Refrigerate assembled cups for up to 2 days; add crackers at serving.",
    substitutions: ["Use Greek yogurt with herbs.", "Add white beans for more fibre."],
    shortcut: "Use grape tomatoes and pre-washed basil.",
    contentAngle: "Red, white, and green makes this a natural cover image for the recipe hub.",
    source: { label: "Skinnytaste — Cottage Cheese Recipes", url: "https://www.skinnytaste.com/healthy-cottage-cheese-recipes/", note: "Cooper Fitness adaptation from the source collection." },
  }),
  defineRecipe({
    slug: "whole-food-trail-mix",
    title: "Whole-Food Trail Mix",
    summary: "A measured mix of nuts, seeds, roasted chickpeas, and dried fruit for portable energy.",
    category: "snack",
    tags: ["high-fibre", "vegetarian", "make-ahead"],
    activeMinutes: 5,
    totalMinutes: 5,
    servings: 8,
    nutrition: { calories: 289, protein: 8, fat: 17, carbs: 26, fibre: 4 },
    ingredients: ["1 cup almonds", "1/2 cup pumpkin seeds", "1 cup roasted chickpeas", "1/2 cup unsweetened dried fruit", "1/2 cup unsweetened coconut flakes", "1/4 cup chopped dark chocolate (optional)"],
    steps: ["Combine all ingredients in a large jar.", "Portion into small bags or containers.", "Keep the serving size measured because nuts and dried fruit are calorie-dense."],
    storage: "Keep sealed in the pantry for 2 weeks.",
    substitutions: ["Use walnuts, sunflower seeds, or roasted edamame.", "Use raisins, cranberries, or dried apricot."],
    shortcut: "Buy unsalted nuts and roasted chickpeas in bulk bins.",
    contentAngle: "A simple ‘portion it once, stop guessing all week’ message matches Cooper’s nutrition direction.",
    source: { label: "Budget Bytes — Homemade Granola Bars", url: "https://www.budgetbytes.com/granola-bars/", note: "Cooper Fitness trail-mix adaptation from the whole-food snack pattern." },
  }),
];
