import type { Recipe } from "./types";

type RecipeVisual = {
  ingredient: string;
  src: string;
  alt: string;
};

const VISUALS: Record<string, RecipeVisual> = {
  avocado: { ingredient: "Avocado", src: "/recipes/avocado.jpg", alt: "Fresh avocado halves" },
  apple: { ingredient: "Apple", src: "/recipes/unique-v2/apple-chia-peanut-butter-pudding.jpg", alt: "Fresh apple" },
  banana: { ingredient: "Banana", src: "/recipes/banana.jpg", alt: "Ripe bananas" },
  berries: { ingredient: "Berries", src: "/recipes/berries.jpg", alt: "Fresh berries in a bowl" },
  beef: { ingredient: "Lean beef", src: "/recipes/beef.jpg", alt: "Sliced grilled beef" },
  beans: { ingredient: "Beans", src: "/recipes/beans.jpg", alt: "Beans in a white bowl" },
  chicken: { ingredient: "Chicken", src: "/recipes/chicken-alt2.jpg", alt: "Chicken breast" },
  burrito: { ingredient: "Breakfast burrito", src: "/recipes/match-v3/breakfast-burrito-bowl.jpg", alt: "Breakfast burrito" },
  chickenMeatballs: { ingredient: "Chicken meatballs", src: "/recipes/match-v3/marry-me-chicken-meatballs.jpg", alt: "Chicken meatballs" },
  frittata: { ingredient: "Chicken sausage frittata", src: "/recipes/ai-v1/cottage-cheese-chicken-sausage-frittata.jpg", alt: "Cottage cheese chicken sausage frittata" },
  scrambledEggs: { ingredient: "Scrambled eggs", src: "/recipes/ai-v1/cottage-cheese-scrambled-eggs.jpg", alt: "Scrambled eggs" },
  eggMuffin: { ingredient: "Egg muffin", src: "/recipes/ai-v1/egg-white-turkey-bacon-muffins.jpg", alt: "Egg white turkey bacon muffin" },
  loadedEggMuffin: { ingredient: "Loaded egg muffin", src: "/recipes/ai-v1/loaded-egg-muffin-snack.jpg", alt: "Loaded egg muffin" },
  smoothie: { ingredient: "Protein smoothie", src: "/recipes/ai-v1/peanut-butter-banana-protein-smoothie.jpg", alt: "Peanut butter banana protein smoothie" },
  buffaloChickenBowl: { ingredient: "Buffalo chicken bowl", src: "/recipes/ai-v1/buffalo-chicken-rice-bowls.jpg", alt: "Buffalo chicken rice bowl" },
  chickenShawarma: { ingredient: "Chicken shawarma", src: "/recipes/ai-v1/chicken-shawarma-sheet-pan.jpg", alt: "Chicken shawarma sheet pan" },
  chickenTacoBowl: { ingredient: "Chicken taco bowl", src: "/recipes/ai-v1/chicken-taco-rice-bowls.jpg", alt: "Chicken taco rice bowl" },
  greekChickenBowl: { ingredient: "Greek chicken bowl", src: "/recipes/ai-v1/greek-chicken-rice-bowls.jpg", alt: "Greek chicken rice bowl" },
  honeySrirachaChickenBowl: { ingredient: "Honey sriracha chicken", src: "/recipes/ai-v1/honey-sriracha-chicken-broccoli-bowls.jpg", alt: "Honey sriracha chicken and broccoli bowl" },
  asianChickenSalad: { ingredient: "Asian chicken salad", src: "/recipes/ai-v1/asian-chicken-chili-crisp-salad.jpg", alt: "Asian chicken salad with chili crisp dressing" },
  chickenEggRollBowl: { ingredient: "Chicken egg roll bowl", src: "/recipes/ai-v1/chicken-egg-roll-bowl.jpg", alt: "Chicken egg roll bowl" },
  greekChickenMealPrepBowl: { ingredient: "Greek chicken meal prep bowl", src: "/recipes/ai-v1/greek-chicken-meal-prep-rice-bowl.jpg", alt: "Greek chicken meal prep rice bowl" },
  greekYogurtChickenSalad: { ingredient: "Greek yogurt chicken salad", src: "/recipes/ai-v1/classic-greek-yogurt-chicken-salad.jpg", alt: "Greek yogurt chicken salad" },
  greenGoddessChickenChickpeaSalad: { ingredient: "Green goddess chicken salad", src: "/recipes/ai-v1/green-goddess-chicken-chickpea-salad.jpg", alt: "Green goddess chicken and chickpea salad" },
  pestoChickenPastaSalad: { ingredient: "Pesto chicken pasta salad", src: "/recipes/ai-v1/pesto-chicken-vegetable-pasta-salad.jpg", alt: "Pesto chicken and vegetable pasta salad" },
  thaiChickenSlaw: { ingredient: "Thai chicken slaw", src: "/recipes/ai-v1/thai-inspired-chicken-slaw.jpg", alt: "Thai inspired chicken slaw" },
  cottageCheese: { ingredient: "Cottage cheese", src: "/recipes/yogurt.jpg", alt: "Cottage cheese curds" },
  eggs: { ingredient: "Eggs", src: "/recipes/eggs.jpg", alt: "Eggs ready for breakfast" },
  energyBites: { ingredient: "Energy bites", src: "/recipes/energy-bites.jpg", alt: "Homemade energy bites with nuts" },
  vegetables: { ingredient: "Vegetables", src: "/recipes/vegetables.jpg", alt: "Colourful vegetables in a bowl" },
  broccoli: { ingredient: "Broccoli", src: "/recipes/unique-v2/sheet-pan-roasted-vegetables.jpg", alt: "Broccoli florets" },
  pintoBeans: { ingredient: "Pinto beans", src: "/recipes/unique-v2/mediterranean-bean-salad.jpg", alt: "Pinto beans" },
  blackBeans: { ingredient: "Black beans", src: "/recipes/unique-v2/black-bean-corn-salsa.jpg", alt: "Black beans" },
  chickpeas: { ingredient: "Chickpeas", src: "/recipes/unique-v2/roasted-chickpea-crunch.jpg", alt: "Chickpeas" },
  groundTurkey: { ingredient: "Ground turkey", src: "/recipes/match-v3/ground-turkey.jpg", alt: "Cooked ground turkey" },
  hummus: { ingredient: "Hummus", src: "/recipes/hummus.jpg", alt: "Plain hummus" },
  edamame: { ingredient: "Edamame", src: "/recipes/beans.jpg", alt: "Shelled edamame beans" },
  lentils: { ingredient: "Lentils", src: "/recipes/lentils.jpg", alt: "Dry lentils" },
  nuts: { ingredient: "Nuts & seeds", src: "/recipes/nuts.jpg", alt: "Mixed nuts and seeds" },
  oats: { ingredient: "Oats", src: "/recipes/oats.jpg", alt: "Rolled oats" },
  pasta: { ingredient: "Pasta", src: "/recipes/pasta.jpg", alt: "Pasta with fresh ingredients" },
  potatoes: { ingredient: "Potatoes", src: "/recipes/potatoes.jpg", alt: "Roasted potatoes" },
  rice: { ingredient: "Rice", src: "/recipes/rice.jpg", alt: "Steamed rice in a bowl" },
  salmon: { ingredient: "Salmon", src: "/recipes/salmon.jpg", alt: "Salmon fillet" },
  shrimp: { ingredient: "Shrimp", src: "/recipes/shrimp.jpg", alt: "Fresh shrimp in a bowl" },
  tuna: { ingredient: "Tuna", src: "/recipes/salmon.jpg", alt: "Tuna fish" },
  turkey: { ingredient: "Turkey", src: "/recipes/chicken-alt2.jpg", alt: "Ground turkey" },
  turkeyMeatballs: { ingredient: "Turkey meatballs", src: "/recipes/match-v3/turkey-meatball-marinara-bowls.jpg", alt: "Turkey meatballs" },
  yogurt: { ingredient: "Greek yogurt", src: "/recipes/yogurt.jpg", alt: "Plain Greek yogurt" },
};

const RECIPE_IMAGE_PATHS: Record<string, string> = {
  // `unique-v2` cards intentionally show one staple ingredient only—not the finished recipe.
  "whipped-cottage-cheese-berry-bowl": "/recipes/unique-v2/whipped-cottage-cheese-berry-bowl.jpg",
  "cottage-cheese-scrambled-eggs": "/recipes/ai-v1/cottage-cheese-scrambled-eggs.jpg",
  "high-protein-oat-waffles": "/recipes/unique-v2/high-protein-oat-waffles.jpg",
  "egg-white-turkey-bacon-muffins": "/recipes/ai-v1/egg-white-turkey-bacon-muffins.jpg",
  "cottage-cheese-chicken-sausage-frittata": "/recipes/ai-v1/cottage-cheese-chicken-sausage-frittata.jpg",
  "apple-pie-overnight-oats": "/recipes/unique-v2/apple-pie-overnight-oats.jpg",
  "tropical-yogurt-oat-parfaits": "/recipes/unique-v2/tropical-yogurt-oat-parfaits.jpg",
  "blueberry-banana-baked-oatmeal": "/recipes/unique-v2/blueberry-banana-baked-oatmeal.jpg",
  "breakfast-burrito-bowl": "/recipes/match-v3/breakfast-burrito-bowl.jpg",
  "peanut-butter-banana-protein-smoothie": "/recipes/ai-v1/peanut-butter-banana-protein-smoothie.jpg",
  "lemon-berry-yogurt-bowl": "/recipes/unique-v2/lemon-berry-yogurt-bowl.jpg",
  "banana-nut-protein-oats": "/recipes/unique-v2/banana-nut-protein-oats.jpg",
  "buffalo-chicken-rice-bowls": "/recipes/ai-v1/buffalo-chicken-rice-bowls.jpg",
  "chicken-taco-rice-bowls": "/recipes/ai-v1/chicken-taco-rice-bowls.jpg",
  "ground-turkey-vegetable-stir-fry": "/recipes/match-v3/ground-turkey.jpg",
  "chicken-shawarma-sheet-pan": "/recipes/ai-v1/chicken-shawarma-sheet-pan.jpg",
  "shrimp-fajita-bowls": "/recipes/unique-v2/shrimp-fajita-bowls.jpg",
  "lemon-chili-shrimp-quinoa-bowls": "/recipes/unique-v2/lemon-chili-shrimp-quinoa-bowls.jpg",
  "greek-chicken-rice-bowls": "/recipes/ai-v1/greek-chicken-rice-bowls.jpg",
  "marry-me-chicken-meatballs": "/recipes/match-v3/marry-me-chicken-meatballs.jpg",
  "chicken-piccata-meatball-orzo": "/recipes/match-v3/chicken-piccata-meatball-orzo.jpg",
  "easy-turkey-chili": "/recipes/match-v3/ground-turkey.jpg",
  "mediterranean-turkey-bowls": "/recipes/match-v3/ground-turkey.jpg",
  "ground-turkey-zucchini-skillet": "/recipes/match-v3/ground-turkey.jpg",
  "vegan-quinoa-edamame-bowl": "/recipes/unique-v2/vegan-quinoa-edamame-bowl.jpg",
  "honey-sriracha-chicken-broccoli-bowls": "/recipes/ai-v1/honey-sriracha-chicken-broccoli-bowls.jpg",
  "salmon-vegetable-sheet-pan": "/recipes/unique-v2/salmon-vegetable-sheet-pan.jpg",
  "turkey-meatball-marinara-bowls": "/recipes/match-v3/turkey-meatball-marinara-bowls.jpg",
  "shrimp-cabbage-roll-bowl": "/recipes/unique-v2/shrimp-cabbage-roll-bowl.jpg",
  "cottage-cheese-sweet-potato-beef-bowl": "/recipes/unique-v2/cottage-cheese-sweet-potato-beef-bowl.jpg",
  "tuna-white-bean-salad": "/recipes/unique-v2/tuna-white-bean-salad.jpg",
  "green-goddess-chicken-chickpea-salad": "/recipes/ai-v1/green-goddess-chicken-chickpea-salad.jpg",
  "asian-chicken-chili-crisp-salad": "/recipes/ai-v1/asian-chicken-chili-crisp-salad.jpg",
  "five-ingredient-salmon-salad": "/recipes/unique-v2/five-ingredient-salmon-salad.jpg",
  "classic-greek-yogurt-chicken-salad": "/recipes/ai-v1/classic-greek-yogurt-chicken-salad.jpg",
  "tuna-egg-salad-crunch-box": "/recipes/unique-v2/tuna-egg-salad-crunch-box.jpg",
  "lentil-crunch-salad": "/recipes/unique-v2/lentil-crunch-salad.jpg",
  "mediterranean-bean-salad": "/recipes/unique-v2/mediterranean-bean-salad.jpg",
  "thai-inspired-chicken-slaw": "/recipes/ai-v1/thai-inspired-chicken-slaw.jpg",
  "chicken-egg-roll-bowl": "/recipes/ai-v1/chicken-egg-roll-bowl.jpg",
  "greek-chicken-meal-prep-rice-bowl": "/recipes/ai-v1/greek-chicken-meal-prep-rice-bowl.jpg",
  "pesto-chicken-vegetable-pasta-salad": "/recipes/ai-v1/pesto-chicken-vegetable-pasta-salad.jpg",
  "lemon-dijon-yogurt-dressing": "/recipes/unique-v2/lemon-dijon-yogurt-dressing.jpg",
  "green-goddess-yogurt-sauce": "/recipes/unique-v2/green-goddess-yogurt-sauce.jpg",
  "freezer-brown-rice-quinoa-blend": "/recipes/unique-v2/freezer-brown-rice-quinoa-blend.jpg",
  "sheet-pan-roasted-vegetables": "/recipes/unique-v2/sheet-pan-roasted-vegetables.jpg",
  "freezer-chicken-turkey-meatballs": "/recipes/match-v3/freezer-chicken-turkey-meatballs.jpg",
  "black-bean-corn-salsa": "/recipes/unique-v2/black-bean-corn-salsa.jpg",
  "edamame-hummus-crunch-dip": "/recipes/unique-v2/edamame-hummus-crunch-dip.jpg",
  "make-ahead-oat-jar-base": "/recipes/unique-v2/make-ahead-oat-jar-base.jpg",
  "apple-chia-peanut-butter-pudding": "/recipes/unique-v2/apple-chia-peanut-butter-pudding.jpg",
  "greek-cottage-cheese-snack-bowl": "/recipes/unique-v2/greek-cottage-cheese-snack-bowl.jpg",
  "edamame-hummus-vegetable-cups": "/recipes/unique-v2/edamame-hummus-vegetable-cups.jpg",
  "loaded-egg-muffin-snack": "/recipes/ai-v1/loaded-egg-muffin-snack.jpg",
  "berry-cottage-cheese-breakfast-snack": "/recipes/unique-v2/berry-cottage-cheese-breakfast-snack.jpg",
  "roasted-chickpea-crunch": "/recipes/unique-v2/roasted-chickpea-crunch.jpg",
  "greek-yogurt-berry-nut-cup": "/recipes/unique-v2/greek-yogurt-berry-nut-cup.jpg",
  "tuna-cucumber-boats": "/recipes/unique-v2/tuna-cucumber-boats.jpg",
  "cottage-cheese-caprese-cups": "/recipes/unique-v2/cottage-cheese-caprese-cups.jpg",
  "whole-food-trail-mix": "/recipes/unique-v2/whole-food-trail-mix.jpg",
};

const RULES: Array<{ key: keyof typeof VISUALS; terms: string[] }> = [
  { key: "energyBites", terms: ["energy bite", "trail mix"] },
  { key: "hummus", terms: ["hummus"] },
  { key: "shrimp", terms: ["shrimp", "prawn"] },
  { key: "salmon", terms: ["salmon"] },
  { key: "tuna", terms: ["tuna"] },
  { key: "chicken", terms: ["chicken"] },
  { key: "beef", terms: ["beef"] },
  { key: "turkey", terms: ["turkey"] },
  { key: "avocado", terms: ["avocado"] },
  { key: "berries", terms: ["berries", "berry", "blueberry", "strawberry"] },
  { key: "banana", terms: ["banana"] },
  { key: "eggs", terms: ["egg"] },
  { key: "cottageCheese", terms: ["cottage cheese"] },
  { key: "yogurt", terms: ["yogurt", "kefir"] },
  { key: "oats", terms: ["oat", "granola"] },
  { key: "pasta", terms: ["pasta", "orzo"] },
  { key: "rice", terms: ["rice"] },
  { key: "potatoes", terms: ["potato"] },
  { key: "lentils", terms: ["lentil"] },
  { key: "beans", terms: ["bean", "chickpea"] },
  { key: "nuts", terms: ["nut", "almond", "peanut", "seed", "tahini"] },
  { key: "vegetables", terms: ["vegetable", "broccoli", "cabbage", "carrot", "zucchini", "spinach"] },
];

// Recipe titles provide a more reliable staple signal than ingredient order,
// especially for oat, yogurt, berry, and egg breakfasts.
const STAPLES_BY_SLUG: Record<string, keyof typeof VISUALS> = {
  "whipped-cottage-cheese-berry-bowl": "cottageCheese",
  "cottage-cheese-scrambled-eggs": "scrambledEggs",
  "high-protein-oat-waffles": "oats",
  "egg-white-turkey-bacon-muffins": "eggMuffin",
  "cottage-cheese-chicken-sausage-frittata": "frittata",
  "apple-pie-overnight-oats": "oats",
  "tropical-yogurt-oat-parfaits": "yogurt",
  "blueberry-banana-baked-oatmeal": "oats",
  "breakfast-burrito-bowl": "burrito",
  "peanut-butter-banana-protein-smoothie": "smoothie",
  "lemon-berry-yogurt-bowl": "berries",
  "banana-nut-protein-oats": "oats",
  "tuna-white-bean-salad": "tuna",
  "green-goddess-chicken-chickpea-salad": "greenGoddessChickenChickpeaSalad",
  "asian-chicken-chili-crisp-salad": "asianChickenSalad",
  "five-ingredient-salmon-salad": "salmon",
  "classic-greek-yogurt-chicken-salad": "greekYogurtChickenSalad",
  "tuna-egg-salad-crunch-box": "tuna",
  "lentil-crunch-salad": "lentils",
  "mediterranean-bean-salad": "pintoBeans",
  "thai-inspired-chicken-slaw": "thaiChickenSlaw",
  "chicken-egg-roll-bowl": "chickenEggRollBowl",
  "greek-chicken-meal-prep-rice-bowl": "greekChickenMealPrepBowl",
  "pesto-chicken-vegetable-pasta-salad": "pestoChickenPastaSalad",
  "buffalo-chicken-rice-bowls": "buffaloChickenBowl",
  "chicken-taco-rice-bowls": "chickenTacoBowl",
  "ground-turkey-vegetable-stir-fry": "groundTurkey",
  "chicken-shawarma-sheet-pan": "chickenShawarma",
  "shrimp-fajita-bowls": "shrimp",
  "lemon-chili-shrimp-quinoa-bowls": "shrimp",
  "greek-chicken-rice-bowls": "greekChickenBowl",
  "marry-me-chicken-meatballs": "chickenMeatballs",
  "chicken-piccata-meatball-orzo": "chickenMeatballs",
  "easy-turkey-chili": "groundTurkey",
  "mediterranean-turkey-bowls": "groundTurkey",
  "ground-turkey-zucchini-skillet": "groundTurkey",
  "vegan-quinoa-edamame-bowl": "edamame",
  "honey-sriracha-chicken-broccoli-bowls": "honeySrirachaChickenBowl",
  "salmon-vegetable-sheet-pan": "salmon",
  "turkey-meatball-marinara-bowls": "turkeyMeatballs",
  "shrimp-cabbage-roll-bowl": "shrimp",
  "cottage-cheese-sweet-potato-beef-bowl": "beef",
  "lemon-dijon-yogurt-dressing": "yogurt",
  "green-goddess-yogurt-sauce": "yogurt",
  "freezer-brown-rice-quinoa-blend": "rice",
  "sheet-pan-roasted-vegetables": "broccoli",
  "freezer-chicken-turkey-meatballs": "chickenMeatballs",
  "black-bean-corn-salsa": "blackBeans",
  "edamame-hummus-crunch-dip": "hummus",
  "make-ahead-oat-jar-base": "oats",
  "apple-chia-peanut-butter-pudding": "apple",
  "greek-cottage-cheese-snack-bowl": "cottageCheese",
  "edamame-hummus-vegetable-cups": "hummus",
  "loaded-egg-muffin-snack": "loadedEggMuffin",
  "berry-cottage-cheese-breakfast-snack": "berries",
  "roasted-chickpea-crunch": "chickpeas",
  "greek-yogurt-berry-nut-cup": "yogurt",
  "tuna-cucumber-boats": "tuna",
  "cottage-cheese-caprese-cups": "cottageCheese",
  "whole-food-trail-mix": "nuts",
};

const FALLBACK = VISUALS.vegetables;

export function getRecipeVisual(recipe: Recipe): RecipeVisual {
  const searchable = `${recipe.title} ${recipe.ingredients.join(" ")}`.toLowerCase();
  const staple = STAPLES_BY_SLUG[recipe.slug];
  const match = RULES.find((rule) => rule.terms.some((term) => searchable.includes(term)));
  const base = staple ? VISUALS[staple] : match ? VISUALS[match.key] : FALLBACK;
  const src = RECIPE_IMAGE_PATHS[recipe.slug] ?? base.src;

  return {
    ...base,
    src,
    alt: `${recipe.title} featuring ${base.ingredient}`,
  };
}
