import type { Recipe } from "./types";

type RecipeVisual = {
  ingredient: string;
  src: string;
  alt: string;
};

const VISUALS: Record<string, RecipeVisual> = {
  avocado: { ingredient: "Avocado", src: "/recipes/avocado.jpg", alt: "Fresh avocado halves" },
  banana: { ingredient: "Banana", src: "/recipes/banana.jpg", alt: "Ripe bananas" },
  berries: { ingredient: "Berries", src: "/recipes/berries.jpg", alt: "Fresh berries in a bowl" },
  beef: { ingredient: "Lean beef", src: "/recipes/beef.jpg", alt: "Sliced grilled beef" },
  beans: { ingredient: "Beans", src: "/recipes/beans.jpg", alt: "Beans in a white bowl" },
  chicken: { ingredient: "Chicken", src: "/recipes/chicken-alt2.jpg", alt: "Sliced chicken with rice and vegetables" },
  cottageCheese: { ingredient: "Cottage cheese", src: "/recipes/yogurt.jpg", alt: "Creamy yogurt bowl with fresh fruit" },
  eggs: { ingredient: "Eggs", src: "/recipes/eggs.jpg", alt: "Eggs ready for breakfast" },
  energyBites: { ingredient: "Energy bites", src: "/recipes/energy-bites.jpg", alt: "Homemade energy bites with nuts" },
  vegetables: { ingredient: "Vegetables", src: "/recipes/vegetables.jpg", alt: "Colourful vegetables in a bowl" },
  hummus: { ingredient: "Hummus", src: "/recipes/hummus.jpg", alt: "Hummus with olive oil and herbs" },
  edamame: { ingredient: "Edamame", src: "/recipes/beans.jpg", alt: "Shelled edamame beans" },
  lentils: { ingredient: "Lentils", src: "/recipes/lentils.jpg", alt: "Seasoned lentils in a bowl" },
  nuts: { ingredient: "Nuts & seeds", src: "/recipes/nuts.jpg", alt: "Mixed nuts and seeds" },
  oats: { ingredient: "Oats", src: "/recipes/oats.jpg", alt: "Warm oats in a breakfast bowl" },
  pasta: { ingredient: "Pasta", src: "/recipes/pasta.jpg", alt: "Pasta with fresh ingredients" },
  potatoes: { ingredient: "Potatoes", src: "/recipes/potatoes.jpg", alt: "Roasted potatoes" },
  rice: { ingredient: "Rice", src: "/recipes/rice.jpg", alt: "Steamed rice in a bowl" },
  salmon: { ingredient: "Salmon", src: "/recipes/salmon.jpg", alt: "Cooked salmon with vegetables" },
  shrimp: { ingredient: "Shrimp", src: "/recipes/shrimp.jpg", alt: "Fresh shrimp in a bowl" },
  tuna: { ingredient: "Tuna", src: "/recipes/salmon.jpg", alt: "Fresh fish with vegetables" },
  turkey: { ingredient: "Turkey", src: "/recipes/chicken-alt2.jpg", alt: "Sliced turkey with rice and vegetables" },
  yogurt: { ingredient: "Greek yogurt", src: "/recipes/yogurt.jpg", alt: "Greek yogurt with fruit" },
};

const RECIPE_IMAGE_PATHS: Record<string, string> = {
  "whipped-cottage-cheese-berry-bowl": "/recipes/unique-v2/whipped-cottage-cheese-berry-bowl.jpg",
  "cottage-cheese-scrambled-eggs": "/recipes/unique-v2/cottage-cheese-scrambled-eggs.jpg",
  "high-protein-oat-waffles": "/recipes/unique-v2/high-protein-oat-waffles.jpg",
  "egg-white-turkey-bacon-muffins": "/recipes/unique-v2/egg-white-turkey-bacon-muffins.jpg",
  "cottage-cheese-chicken-sausage-frittata": "/recipes/unique-v2/cottage-cheese-chicken-sausage-frittata.jpg",
  "apple-pie-overnight-oats": "/recipes/unique-v2/apple-pie-overnight-oats.jpg",
  "tropical-yogurt-oat-parfaits": "/recipes/unique-v2/tropical-yogurt-oat-parfaits.jpg",
  "blueberry-banana-baked-oatmeal": "/recipes/unique-v2/blueberry-banana-baked-oatmeal.jpg",
  "breakfast-burrito-bowl": "/recipes/unique-v2/breakfast-burrito-bowl.jpg",
  "peanut-butter-banana-protein-smoothie": "/recipes/unique-v2/peanut-butter-banana-protein-smoothie.jpg",
  "lemon-berry-yogurt-bowl": "/recipes/unique-v2/lemon-berry-yogurt-bowl.jpg",
  "banana-nut-protein-oats": "/recipes/unique-v2/banana-nut-protein-oats.jpg",
  "buffalo-chicken-rice-bowls": "/recipes/unique-v2/buffalo-chicken-rice-bowls.jpg",
  "chicken-taco-rice-bowls": "/recipes/unique-v2/chicken-taco-rice-bowls.jpg",
  "ground-turkey-vegetable-stir-fry": "/recipes/unique-v2/ground-turkey-vegetable-stir-fry.jpg",
  "chicken-shawarma-sheet-pan": "/recipes/unique-v2/chicken-shawarma-sheet-pan.jpg",
  "shrimp-fajita-bowls": "/recipes/unique-v2/shrimp-fajita-bowls.jpg",
  "lemon-chili-shrimp-quinoa-bowls": "/recipes/unique-v2/lemon-chili-shrimp-quinoa-bowls.jpg",
  "greek-chicken-rice-bowls": "/recipes/unique-v2/greek-chicken-rice-bowls.jpg",
  "marry-me-chicken-meatballs": "/recipes/unique-v2/marry-me-chicken-meatballs.jpg",
  "chicken-piccata-meatball-orzo": "/recipes/unique-v2/chicken-piccata-meatball-orzo.jpg",
  "easy-turkey-chili": "/recipes/unique-v2/easy-turkey-chili.jpg",
  "mediterranean-turkey-bowls": "/recipes/unique-v2/mediterranean-turkey-bowls.jpg",
  "ground-turkey-zucchini-skillet": "/recipes/unique-v2/ground-turkey-zucchini-skillet.jpg",
  "vegan-quinoa-edamame-bowl": "/recipes/unique-v2/vegan-quinoa-edamame-bowl.jpg",
  "honey-sriracha-chicken-broccoli-bowls": "/recipes/unique-v2/honey-sriracha-chicken-broccoli-bowls.jpg",
  "salmon-vegetable-sheet-pan": "/recipes/unique-v2/salmon-vegetable-sheet-pan.jpg",
  "turkey-meatball-marinara-bowls": "/recipes/unique-v2/turkey-meatball-marinara-bowls.jpg",
  "shrimp-cabbage-roll-bowl": "/recipes/unique-v2/shrimp-cabbage-roll-bowl.jpg",
  "cottage-cheese-sweet-potato-beef-bowl": "/recipes/unique-v2/cottage-cheese-sweet-potato-beef-bowl.jpg",
  "tuna-white-bean-salad": "/recipes/unique-v2/tuna-white-bean-salad.jpg",
  "green-goddess-chicken-chickpea-salad": "/recipes/unique-v2/green-goddess-chicken-chickpea-salad.jpg",
  "asian-chicken-chili-crisp-salad": "/recipes/unique-v2/asian-chicken-chili-crisp-salad.jpg",
  "five-ingredient-salmon-salad": "/recipes/unique-v2/five-ingredient-salmon-salad.jpg",
  "classic-greek-yogurt-chicken-salad": "/recipes/unique-v2/classic-greek-yogurt-chicken-salad.jpg",
  "tuna-egg-salad-crunch-box": "/recipes/unique-v2/tuna-egg-salad-crunch-box.jpg",
  "lentil-crunch-salad": "/recipes/unique-v2/lentil-crunch-salad.jpg",
  "mediterranean-bean-salad": "/recipes/unique-v2/mediterranean-bean-salad.jpg",
  "thai-inspired-chicken-slaw": "/recipes/unique-v2/thai-inspired-chicken-slaw.jpg",
  "chicken-egg-roll-bowl": "/recipes/unique-v2/chicken-egg-roll-bowl.jpg",
  "greek-chicken-meal-prep-rice-bowl": "/recipes/unique-v2/greek-chicken-meal-prep-rice-bowl.jpg",
  "pesto-chicken-vegetable-pasta-salad": "/recipes/unique-v2/pesto-chicken-vegetable-pasta-salad.jpg",
  "lemon-dijon-yogurt-dressing": "/recipes/unique-v2/lemon-dijon-yogurt-dressing.jpg",
  "green-goddess-yogurt-sauce": "/recipes/unique-v2/green-goddess-yogurt-sauce.jpg",
  "freezer-brown-rice-quinoa-blend": "/recipes/unique-v2/freezer-brown-rice-quinoa-blend.jpg",
  "sheet-pan-roasted-vegetables": "/recipes/unique-v2/sheet-pan-roasted-vegetables.jpg",
  "freezer-chicken-turkey-meatballs": "/recipes/unique-v2/freezer-chicken-turkey-meatballs.jpg",
  "black-bean-corn-salsa": "/recipes/unique-v2/black-bean-corn-salsa.jpg",
  "edamame-hummus-crunch-dip": "/recipes/unique-v2/edamame-hummus-crunch-dip.jpg",
  "make-ahead-oat-jar-base": "/recipes/unique-v2/make-ahead-oat-jar-base.jpg",
  "apple-chia-peanut-butter-pudding": "/recipes/unique-v2/apple-chia-peanut-butter-pudding.jpg",
  "greek-cottage-cheese-snack-bowl": "/recipes/unique-v2/greek-cottage-cheese-snack-bowl.jpg",
  "edamame-hummus-vegetable-cups": "/recipes/unique-v2/edamame-hummus-vegetable-cups.jpg",
  "loaded-egg-muffin-snack": "/recipes/unique-v2/loaded-egg-muffin-snack.jpg",
  "berry-cottage-cheese-breakfast-snack": "/recipes/unique-v2/berry-cottage-cheese-breakfast-snack.jpg",
  "roasted-chickpea-crunch": "/recipes/unique-v2/roasted-chickpea-crunch.jpg",
  "greek-yogurt-berry-nut-cup": "/recipes/unique-v2/greek-yogurt-berry-nut-cup.jpg",
  "tuna-cucumber-boats": "/recipes/unique-v2/tuna-cucumber-boats.jpg",
  "cottage-cheese-caprese-cups": "/recipes/unique-v2/cottage-cheese-caprese-cups.jpg",
  "whole-food-trail-mix": "/recipes/unique-v2/whole-food-trail-mix.jpg",
};

const RULES: Array<{ key: keyof typeof VISUALS; terms: string[] }> = [
  { key: "energyBites", terms: ["energy bite", "trail mix"] },
  { key: "hummus", terms: ["hummus"] },
  { key: "shrimp", terms: ["shrimp", "prawn"] },
  { key: "salmon", terms: ["salmon"] },
  { key: "tuna", terms: ["tuna"] },
  { key: "chicken", terms: ["chicken"] },
  { key: "beef", terms: ["beef"] },
  { key: "turkey", terms: ["turkey"] },
  { key: "avocado", terms: ["avocado"] },
  { key: "berries", terms: ["berries", "berry", "blueberry", "strawberry"] },
  { key: "banana", terms: ["banana"] },
  { key: "eggs", terms: ["egg"] },
  { key: "cottageCheese", terms: ["cottage cheese"] },
  { key: "yogurt", terms: ["yogurt", "kefir"] },
  { key: "oats", terms: ["oat", "granola"] },
  { key: "pasta", terms: ["pasta", "orzo"] },
  { key: "rice", terms: ["rice"] },
  { key: "potatoes", terms: ["potato"] },
  { key: "lentils", terms: ["lentil"] },
  { key: "beans", terms: ["bean", "chickpea"] },
  { key: "nuts", terms: ["nut", "almond", "peanut", "seed", "tahini"] },
  { key: "vegetables", terms: ["vegetable", "broccoli", "cabbage", "carrot", "zucchini", "spinach"] },
];

// Recipe titles provide a more reliable staple signal than ingredient order,
// especially for oat, yogurt, berry, and egg breakfasts.
const STAPLES_BY_SLUG: Record<string, keyof typeof VISUALS> = {
  "whipped-cottage-cheese-berry-bowl": "cottageCheese",
  "cottage-cheese-scrambled-eggs": "eggs",
  "high-protein-oat-waffles": "oats",
  "egg-white-turkey-bacon-muffins": "eggs",
  "cottage-cheese-chicken-sausage-frittata": "eggs",
  "apple-pie-overnight-oats": "oats",
  "tropical-yogurt-oat-parfaits": "yogurt",
  "blueberry-banana-baked-oatmeal": "oats",
  "breakfast-burrito-bowl": "eggs",
  "peanut-butter-banana-protein-smoothie": "banana",
  "lemon-berry-yogurt-bowl": "berries",
  "banana-nut-protein-oats": "oats",
  "tuna-white-bean-salad": "tuna",
  "green-goddess-chicken-chickpea-salad": "chicken",
  "asian-chicken-chili-crisp-salad": "chicken",
  "five-ingredient-salmon-salad": "salmon",
  "classic-greek-yogurt-chicken-salad": "chicken",
  "tuna-egg-salad-crunch-box": "tuna",
  "lentil-crunch-salad": "lentils",
  "mediterranean-bean-salad": "beans",
  "thai-inspired-chicken-slaw": "chicken",
  "chicken-egg-roll-bowl": "chicken",
  "greek-chicken-meal-prep-rice-bowl": "chicken",
  "pesto-chicken-vegetable-pasta-salad": "chicken",
  "buffalo-chicken-rice-bowls": "chicken",
  "chicken-taco-rice-bowls": "chicken",
  "ground-turkey-vegetable-stir-fry": "turkey",
  "chicken-shawarma-sheet-pan": "chicken",
  "shrimp-fajita-bowls": "shrimp",
  "lemon-chili-shrimp-quinoa-bowls": "shrimp",
  "greek-chicken-rice-bowls": "chicken",
  "marry-me-chicken-meatballs": "chicken",
  "chicken-piccata-meatball-orzo": "chicken",
  "easy-turkey-chili": "turkey",
  "mediterranean-turkey-bowls": "turkey",
  "ground-turkey-zucchini-skillet": "turkey",
  "vegan-quinoa-edamame-bowl": "edamame",
  "honey-sriracha-chicken-broccoli-bowls": "chicken",
  "salmon-vegetable-sheet-pan": "salmon",
  "turkey-meatball-marinara-bowls": "turkey",
  "shrimp-cabbage-roll-bowl": "shrimp",
  "cottage-cheese-sweet-potato-beef-bowl": "beef",
  "lemon-dijon-yogurt-dressing": "yogurt",
  "green-goddess-yogurt-sauce": "yogurt",
  "freezer-brown-rice-quinoa-blend": "rice",
  "sheet-pan-roasted-vegetables": "vegetables",
  "freezer-chicken-turkey-meatballs": "chicken",
  "black-bean-corn-salsa": "beans",
  "edamame-hummus-crunch-dip": "hummus",
  "make-ahead-oat-jar-base": "oats",
  "apple-chia-peanut-butter-pudding": "nuts",
  "greek-cottage-cheese-snack-bowl": "cottageCheese",
  "edamame-hummus-vegetable-cups": "hummus",
  "loaded-egg-muffin-snack": "eggs",
  "berry-cottage-cheese-breakfast-snack": "berries",
  "roasted-chickpea-crunch": "beans",
  "greek-yogurt-berry-nut-cup": "yogurt",
  "tuna-cucumber-boats": "tuna",
  "cottage-cheese-caprese-cups": "cottageCheese",
  "whole-food-trail-mix": "nuts",
};

const FALLBACK = VISUALS.vegetables;

export function getRecipeVisual(recipe: Recipe): RecipeVisual {
  const searchable = `${recipe.title} ${recipe.ingredients.join(" ")}`.toLowerCase();
  const staple = STAPLES_BY_SLUG[recipe.slug];
  const match = RULES.find((rule) => rule.terms.some((term) => searchable.includes(term)));
  const base = staple ? VISUALS[staple] : match ? VISUALS[match.key] : FALLBACK;
  const src = RECIPE_IMAGE_PATHS[recipe.slug] ?? base.src;

  return {
    ...base,
    src,
    alt: `${recipe.title} featuring ${base.ingredient}`,
  };
}
